// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.
// Source: «Final Website Instructions_DRAFT Sept 1 2026 .docx.md», lines 113–247.

import { pageSchema } from '../schemas'

export const ABOUT = pageSchema.parse({
  slug: 'about',
  title: 'About',
  sections: [
    {
      id: 'our-logo-the-ceiba',
      title: 'Our Logo - The Ceiba',
      paragraphs: [
        'We chose the ceiba because its symbolism mirrors our own: deep roots, steady strength and open growth. A balance the Maya recognized long before we did, seeing the ceiba as the axis connecting earth and sky.',
        'Look closely at our mark and you’ll see three branches reaching upward and three roots reaching downward, meeting at a single point. That point is touched with gold, the only accent colour in our identity. It represents one client, one dedicated team and one shared purpose: grounded, precise treatment built entirely around you.',
      ],
    },
    {
      id: 'about-the-new-practice',
      title: 'ABOUT THE NEW PRACTICE',
      subtitle: 'From Kusnacht to Puerto Aventuras',
      header: 'A New Standard in Private Behavioural Healthcare',
      paragraphs: [
        'The New Practice is the result of more than twenty five years of experience working with individuals and families affected by addiction, trauma, eating disorders, burnout and other behavioural health challenges.',
        'It is also the continuation of a model of care that began in Switzerland more than twenty years ago…',
        'In 2007, Lowell Monkhouse began developing The Kusnacht Practice, with the objective of creating an alternative to traditional residential treatment. At that time, most programs were built around group therapy, fixed schedules, and institutional settings. While these models were effective for some people, they were often less suitable for individuals with significant wealth, demanding careers, public profiles, or complex personal circumstances.',
        'This new approach is straightforward: rather than asking clients to adapt to a treatment program, the program is built around the client.',
        'That means assembling a multidisciplinary team dedicated to one individual, providing treatment in a private clinical residence rather than an institutional environment, and creating a standard of care that reflects the client’s life experience.',
        'It was based on the belief that people recover more effectively when they feel safe, respected, and understood. For someone accustomed to privacy, security, independence, and personal responsibility, removing unnecessary institutional barriers allows them to focus their energy on recovery rather than adapting to an institutional environment.',
        'Today, The New Practice builds upon those original principles while reflecting what has been learned over the past two decades. Our model places even greater emphasis on trauma and the inner child as the basis of most of the disorders that we treat, continuity of treatment, family involvement, nervous system regulation, biochemical restoration, and long-term recovery management.',
      ],
    },
    {
      id: 'a-message-from-the-founder',
      title: 'A MESSAGE FROM THE FOUNDER',
      paragraphs: [
        'When I first entered the addiction treatment field, I believed that if people received good therapy they would recover. Experience taught me that recovery is more complicated than that.',
        'Over the years, I came to understand that lasting change depends on many factors. Trauma, family function, physical health, brain chemistry, stress, purpose, and the quality of the therapeutic relationship all influence the outcome.',
        'Perhaps most importantly I learned that recovery doesn’t begin when someone enters treatment and it certainly doesn’t end when they leave.',
        'In 2007 I founded The Kusnacht Practice, based in Switzerland. My objective was to create a model that combined outstanding clinical care with the flexibility, privacy, and individual attention that many successful individuals require.',
        'The philosophy was simple. Clinical excellence would always come first, but it would be delivered in an environment that reflected the client’s life experience rather than asking the client to adapt to an institutional setting. Privacy, dignity, flexibility, and exceptional personal service were not luxuries, they were important components of effective treatment for the people we served. During those years I had the privilege of working alongside exceptional colleagues.',
        'I remain proud of what we built together and of the many talented people who helped shape a new and unique business and clinical model. Seeing former colleagues establish successful organisations of their own has been both personally rewarding and professionally gratifying. It speaks to their individual abilities and the strength of the ideas that continue to shape private behavioural healthcare in the world today.',
        'The New Practice represents the next stage of that journey.',
        'It incorporates everything I have learned over more than 20 years working with clients, families, and treatment professionals in North America, the Middle East and Europe.',
        'While many aspects of treatment have changed over the years, one belief has only become stronger.',
        'People recover through relationships.',
        'For that reason, continuity of care is one of the foundations of our work. The clinician who supports you during treatment remains involved throughout your transition home when clinically appropriate. We believe that maintaining trusted therapeutic relationships during this period makes an important difference to long-term recovery.',
        'Our goal has never been simply to help people stop drinking, stop using drugs, heal the adult child or reduce psychiatric symptoms. Our goal is to help people build lives they genuinely want to live. That is the purpose of The New Practice.',
        'Thank you for taking the time to learn about our work. I look forward to the opportunity to meet you.',
      ],
      signature: {
        name: 'Lowell Monkhouse',
        role: 'Founder & Clinical Director',
      },
    },
    {
      id: 'puerto-aventuras',
      title: 'PUERTO AVENTURAS',
      paragraphs: [],
      subsections: [
        {
          id: 'a-place-chosen-for-healing',
          title: 'A Place Chosen for Healing',
          paragraphs: [
            'The location of treatment can be as important as the treatment itself.',
            'For that reason, The New Practice is located in Puerto Aventuras, a private gated community on Mexico’s Riviera Maya, where the natural environment, climate, privacy, and pace of life support recovery in ways that are difficult to achieve in large cities or institutional settings.',
            'We did not choose Puerto Aventuras because it is beautiful. We chose it because it is therapeutic.',
            'Here, clients are removed from the pressures, distractions, and demands that often contribute to emotional exhaustion.',
            'Healing begins in an environment where people can finally slow down.',
          ],
        },
        {
          id: 'privacy-safety-and-peace',
          title: 'Privacy, Safety and Peace',
          paragraphs: [
            'Puerto Aventuras is one of the Riviera Maya’s most secure residential communities.',
            'The marina, quiet residential streets, tropical gardens, ancient Mayan canals, beaches and relaxed atmosphere provide an exceptional degree of privacy for individuals and families who value discretion.',
            'Unlike busy tourist destinations, Puerto Aventuras offers a peaceful environment where clients can focus entirely on recovery without unnecessary interruption.',
            'Many of our clients are accustomed to living under constant pressure and public scrutiny.',
            'Here they are able to experience something that has often been absent from their lives for many years: Peace.',
          ],
        },
        {
          id: 'the-caribbean-sea',
          title: 'The Caribbean Sea',
          paragraphs: [
            'The Caribbean Sea forms part of everyday life at The New Practice.',
            'Morning walks beside the water, quiet reflection overlooking a canal, gentle exercise, and time spent outdoors all contribute to reducing stress and regulating the nervous system.',
            'Natural sunlight and the jungle support healthy circadian rhythms, improves sleep, and contributes to emotional wellbeing.',
            'The slower rhythm of life encourages mindfulness, reflection, and recovery.',
          ],
        },
        {
          id: 'the-healing-power-of-the-mayan-jungle',
          title: 'The Healing Power of the Mayan Jungle',
          paragraphs: [
            'For thousands of years, the ancient Maya regarded the surrounding jungle as a place of healing, wisdom, and spiritual connection.',
            'Today, modern research increasingly supports what indigenous cultures have understood for generations.',
            'Time spent in nature can reduce stress hormones, improve mood, lower blood pressure, enhance immune function, improve sleep, and promote emotional wellbeing.',
            'The jungles of the Riviera Maya offer a remarkable environment for reflection and restoration.',
            'Surrounded by ancient trees, tropical vegetation, cenotes, and abundant wildlife, clients often experience a profound sense of calm that is difficult to find within modern urban life.',
            'Nature becomes part of the therapeutic process.',
          ],
        },
      ],
    },
    {
      id: 'our-principles',
      title: 'Our principles',
      paragraphs: ['Everything we do is guided by a number of fundamental principles.'],
      definitions: [
        {
          term: 'Individualised Care',
          description: 'Every client is different. Every treatment program should be different.',
        },
        {
          term: 'Clinical Excellence',
          description:
            'We bring together experienced professionals from multiple disciplines who work as one integrated team.',
        },
        {
          term: 'Continuity of Care',
          description:
            'Recovery is a process, not an event. We believe continuity of therapeutic relationships plays an important role in achieving lasting change.',
        },
        {
          term: 'Family Involvement',
          description:
            'Where appropriate, we involve family members in treatment, helping to restore understanding, communication, and healthier relationships.',
        },
        {
          term: 'Respect for the Individual',
          description:
            'We believe treatment is most effective when it respects the client’s dignity, privacy, responsibilities, and way of life.',
        },
        {
          term: 'Sustainable Recovery',
          description:
            'Success is not measured by the day a client leaves treatment. It is measured by the quality of the life they build afterwards.',
        },
      ],
    },
  ],
})
