// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.
// Source: «Final Website Instructions_DRAFT Sept 1 2026 .docx.md», lines 1198–1250.
// contact.website is a PLACEHOLDER: the document leaves Direct Telephone / Email / Website blank; phone and email resolve to brand.ts. See docs/CONTENT-GAPS.md.

import { contactPageSchema } from '../schemas'
import { BRAND } from '../brand'

export const CONTACT = contactPageSchema.parse({
  slug: 'contact',
  title: 'Contact',
  lead: 'Seeking help for yourself or someone you care about can feel overwhelming.',
  sections: [
    {
      id: 'begin-the-conversation',
      title: 'Begin the Conversation',
      paragraphs: [
        'Whether you are making contact for yourself, a family member, a friend, a colleague, or a client, we understand that every situation is unique and often accompanied by uncertainty.',
        'At The New Practice, every enquiry is handled personally, professionally, and with complete confidentiality. We take the time to understand your circumstances, answer your questions honestly, and help you determine whether The New Practice is the right fit for your needs. If we believe another approach or another organisation would better serve you, we will tell you.',
      ],
    },
    {
      id: 'who-contacts-us',
      title: 'Who Contacts Us',
      paragraphs: [],
      listHeading: 'We welcome confidential enquiries from:',
      list: [
        'Individuals seeking help for themselves',
        'Partners and family members',
        'Friends and colleagues',
        'Physicians and psychiatrists',
        'Psychologists and therapists',
        'Lawyers',
        'Family offices',
        'Private banks and wealth advisors',
        'Corporate executives and business leaders',
        'Human resource professionals',
        'Professional advisers',
        'Concerned loved ones',
      ],
      outro: [
        'Whether you are looking for information, seeking a second opinion, planning an intervention, or exploring treatment options, we are happy to discuss your situation in confidence.',
      ],
    },
    {
      id: 'international-services',
      title: 'International Services',
      paragraphs: [
        'The New Practice is based in Puerto Aventuras, Riviera Maya, Mexico, and works with clients from around the world.',
        'Depending on clinical need, treatment may take place in our private residence, within your own home, or another carefully selected location internationally. We also provide ongoing after care and recovery management services worldwide.',
      ],
    },
    {
      id: 'confidential-consultation',
      title: 'Confidential Consultation',
      paragraphs: ['To arrange a confidential consultation, please contact:'],
    },
  ],
  contact: {
    name: BRAND.founder.name,
    credentials: BRAND.founder.credentials,
    role: BRAND.founder.role,
    phone: BRAND.phone,
    email: BRAND.email,
    locale: BRAND.locale,
    organisation: BRAND.name,
    website: 'thenewpractice.health',
  },
})
