// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.
// Source: «Final Website Instructions_DRAFT Sept 1 2026 .docx.md», lines 1284–1287.

import type { Page } from '../schemas'

export const FEES: Page = {
  slug: 'fees',
  title: 'Cost',
  sections: [
    {
      id: 'cost',
      paragraphs: [
        'Our all-inclusive fee for treatment in Puerto Aventuras is US$55,500 per week plus the cost of your travel and unusual medical expenses. Costs for treatment in your home or another clinical residence in the world will be provided on a case-by-case basis.',
      ],
    },
  ],
}
