// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.
// Source: «Final Website Instructions_DRAFT Sept 1 2026 .docx.md», lines 2–111.

import { homePageSchema } from '../schemas'
import { BRAND } from '../brand'
import { UI } from '../ui'

export const HOME = homePageSchema.parse({
  slug: 'home',
  title: 'Home',
  hero: {
    title: 'A New Approach to Wellbeing',
    subtitle: 'From Kusnacht to Puerto Aventuras',
    cue: UI.scrollCue,
    audioScript:
      'There is something deeply healing about the Riviera Maya — the power of the ocean, the stillness of the jungle, and the ancient energy of this land. A place where the mind, body and spirit can begin to heal.',
    audioSrc: null,
    videoBrief:
      'Monologue audio over videos of ocean waves and old growth forest…\nVideo: 0:00–0:15 Gentle ocean surf, jungle beginning to emerge; one or two distant tropical birds\nAudio starts over video: 0:03–0:15 — Female voice possibly British, warm, not commercial\nKeep the ocean continuously audible in the background, birds sparse and natural, and avoid music entirely. Should invoke feelings of privacy, luxurious, elemental and restorative\nONLY AUDIO.',
  },
  sections: [
    {
      id: 'private-treatment-without-compromise',
      title: 'Private Treatment Without Compromise',
      subtitle: 'One Client. One Team. One Purpose.',
      paragraphs: [
        'The New Practice is a private behavioural health practice based in Puerto Aventuras, in Mexico’s Riviera Maya. We provide highly individualized treatment for addiction, trauma, eating disorders, mental health conditions, executive burnout, and complex family issues with an emphasis on the inner child.',
        'We treat one client at a time.',
        'Every aspect of your care is built around you. A dedicated multidisciplinary team works exclusively with you and your family to deliver a level of continuity, flexibility, privacy, and clinical attention that cannot be achieved within most treatment centres.',
        'Whether you join us at one of our clinical residences in Puerto Aventuras, in your own home, or somewhere else in the world, our mission remains the same: deliver exceptional clinical care while helping you build the foundation for lasting recovery and a healthier, more fulfilling life.',
      ],
    },
    {
      id: 'recovery-without-interruption',
      title: 'Recovery Without Interruption',
      paragraphs: [
        'Most treatment programs begin when a client arrives and ends when they leave. We believe recovery should be different.',
        'At The New Practice, the therapeutic relationship begins with your first confidential conversation and continues long after you return home.',
        'Throughout your program you are supported by an integrated clinical team working exclusively with you. A dedicated live-in clinician remains by your side throughout treatment and whenever clinically appropriate, accompanies you home to help you successfully transition back into everyday life. Recovery succeeds when trust is never interrupted.',
      ],
    },
    {
      id: 'who-we-help',
      title: 'Who We Help',
      paragraphs: [],
      listHeading:
        'The New Practice provides confidential care for individuals and families experiencing:',
      list: [
        'Alcoholism and other drug use disorders',
        'Trauma and complex trauma',
        'Anxiety and depression',
        'Eating disorders',
        'Gambling compulsivity',
        'Sex and love compulsivity',
        'Executive burnout',
        'Chronic stress',
        'Emotional dysregulation',
        'Family dysfunction and relationship difficulties',
        'Codependency',
        'Major life transitions',
      ],
    },
    {
      id: 'our-philosophy',
      title: 'Our Philosophy',
      paragraphs: [],
      definitions: [
        {
          term: 'One Client at a Time',
          description:
            'Our entire practice is designed around a single client and their family, allowing every decision to be individualized.',
        },
        {
          term: 'A Dedicated Multidisciplinary Team',
          description:
            'Your psychiatrist, psychologist, physician, trauma therapist, nutrition specialist, somatic practitioners, chef, and live-in clinician work together every day toward one shared goal, your recovery.',
        },
        {
          term: 'Continuity of Care',
          description:
            'The therapeutic relationship extends far beyond your stay in the Mayan jungle. Your after care Program begins before you leave, and whenever clinically appropriate, your live-in clinician accompanies you home to support your transition back into everyday life.',
        },
        {
          term: 'Family Integration',
          description:
            'Recovery is rarely an individual journey. We work closely with families to build understanding, restore trust, improve communication, and create an environment that supports lasting change.',
        },
        {
          term: 'Worldwide Care',
          description:
            'When clinically appropriate, members of our team can provide assessment, treatment, family work, intervention, and after care in your own home or another suitable location anywhere in the world.',
        },
      ],
      subsections: [
        {
          id: 'why-the-new-practice',
          title: 'Why The New Practice?',
          paragraphs: [
            'We believe that every individual has an innate capacity to heal when the underlying cause of illness is identified and addressed. Our purpose is not simply to reduce symptoms, but to restore health, resilience, and the ability to live a meaningful purposeful life.',
            'We believe one of the greatest challenges in modern healthcare is the overreliance on pharmaceuticals to suppress symptoms rather than understand and treat the root causes of physical, psychological, and emotional suffering. While symptom relief may sometimes be necessary, we believe that lasting recovery is achieved by identifying and addressing the biological, psychological, nutritional, relational, environmental, and spiritual factors that contribute to illness.',
            'Our approach is comprehensive, individualized, and evidence-informed. We integrate advanced medical assessment, psychiatry, psychology, trauma therapy, nervous system regulation, nutritional medicine, biochemical restoration, movement, sleep optimization, inner child work, and meaningful lifestyle change into a single coordinated treatment experience. Every treatment plan is tailored to the unique needs of the individual rather than applying a standardized model of care.',
            'We believe that the human body and mind possess a remarkable capacity for healing when given the appropriate support. Our role is to remove barriers to recovery, restore physiological balance, resolve psychological distress, strengthen relationships, and empower each client to achieve lasting wellbeing.',
            'Above all, we believe healing occurs within a relationship built on trust, compassion, dignity, and absolute confidentiality. By caring for only one client at a time, we provide an unparalleled level of attention, continuity, and personalization, ensuring that every aspect of care is focused on one goal: restoring health- not simply suppressing symptoms.',
          ],
        },
      ],
    },
    {
      id: 'begin-the-conversation',
      title: 'Begin the Conversation',
      paragraphs: [
        'Seeking help is often one of the most important decisions an individual or family will ever make.',
        'Every enquiry is handled with complete confidentiality.',
        'If you would like to learn more about The New Practice or discuss whether our program is appropriate for you or someone you care about, we invite you to contact us directly.',
      ],
    },
  ],
  contact: {
    name: BRAND.founder.name,
    credentials: BRAND.founder.credentials,
    role: BRAND.founder.role,
    phone: BRAND.phone,
    email: BRAND.email,
    locale: BRAND.locale,
  },
})
