/**
 * LEGAL PAGES — HAND-WRITTEN, ENTIRELY PLACEHOLDER. docs/CONTENT-GAPS.md G3.
 *
 * The client document supplies no privacy policy and no terms. Until their
 * counsel does, `/privacy` and `/terms` render these stubs: section headings
 * only, each followed by one sentence saying the text is pending. Every
 * string is prefixed `PLACEHOLDER — ` so it cannot ship unnoticed, and
 * nothing here states a legal position, a jurisdiction, a retention period
 * or a data practice. Both routes are `noIndex` and left out of the sitemap
 * (`NOINDEX_ROUTES` in nav.ts) while this file is what they render.
 *
 * Not generated by scripts/ingest-content.mjs, which never overwrites it.
 */
import { pageSchema } from '../schemas'

const P = 'PLACEHOLDER — '

const PENDING = `${P}This section is pending review by the client’s counsel; the heading stands for the text it will carry.`

const stub = (id: string, title: string) => ({ id, title: `${P}${title}`, paragraphs: [PENDING] })

export const PRIVACY = pageSchema.parse({
  slug: 'privacy',
  title: `${P}Privacy`,
  lead: `${P}This policy is pending the client’s counsel. Nothing below is in force.`,
  sections: [
    stub('information-we-collect', 'Information we collect'),
    stub('how-information-is-used', 'How information is used'),
    stub('retention-and-security', 'Retention and security'),
    stub('your-rights-and-contact', 'Your rights and how to contact us'),
  ],
})

export const TERMS = pageSchema.parse({
  slug: 'terms',
  title: `${P}Terms`,
  lead: `${P}These terms are pending the client’s counsel. Nothing below is in force.`,
  sections: [
    stub('use-of-this-website', 'Use of this website'),
    stub('clinical-information', 'Clinical information'),
    stub('intellectual-property', 'Intellectual property'),
    stub('governing-law', 'Governing law'),
  ],
})
