/**
 * LEGAL PAGES — HAND-WRITTEN, ENTIRELY PLACEHOLDER. docs/CONTENT-GAPS.md G3.
 *
 * The client document supplies no privacy policy and no terms. Until their
 * counsel does, `/privacy` and `/terms` render these stubs: a title and
 * section headings only, no body text, every string prefixed `PLACEHOLDER — `
 * so it cannot ship unnoticed (owner decision, Task 21: the prefix is the one
 * tolerated marker; no note sentences). Nothing here states a legal position,
 * a jurisdiction, a retention period or a data practice. Both routes are
 * `noIndex` and left out of the sitemap (`NOINDEX_ROUTES` in nav.ts) while
 * this file is what they render.
 *
 * Not generated by scripts/ingest-content.mjs, which never overwrites it.
 */
import type { Page } from '../schemas'

const P = 'PLACEHOLDER — '

const stub = (id: string, title: string) => ({ id, title: `${P}${title}`, paragraphs: [] })

export const PRIVACY: Page = {
  slug: 'privacy',
  title: `${P}Privacy`,
  sections: [
    stub('information-we-collect', 'Information we collect'),
    stub('how-information-is-used', 'How information is used'),
    stub('retention-and-security', 'Retention and security'),
    stub('your-rights-and-contact', 'Your rights and how to contact us'),
  ],
}

export const TERMS: Page = {
  slug: 'terms',
  title: `${P}Terms`,
  sections: [
    stub('use-of-this-website', 'Use of this website'),
    stub('clinical-information', 'Clinical information'),
    stub('intellectual-property', 'Intellectual property'),
    stub('governing-law', 'Governing law'),
  ],
}
