// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.
// Source: «Final Website Instructions_DRAFT Sept 1 2026 .docx.md», lines 1252–1282.

import { letterPageSchema } from '../schemas'

export const PERSONAL_MESSAGE = letterPageSchema.parse({
  slug: 'a-personal-message',
  title: 'A Personal Message',
  eyebrow: 'THANK YOU',
  sections: [
    {
      id: 'letter',
      paragraphs: [
        'Thank you for taking the time to learn about The New Practice.',
        'Over the past four decades I have had the privilege of working with individuals and families from around the world whose lives have been affected by addiction, trauma, eating disorders, mental health challenges, and overwhelming stress.',
        'One lesson has remained constant throughout that journey.',
        'People recover when they are understood, treated with compassion, and provided with the right care by the right people in the right environment.',
        'That belief inspired me to develop The Kusnacht Practice in Switzerland more than twenty years ago, and it continues to guide every aspect of The New Practice today.',
        'If you are considering treatment for yourself or someone you love, I invite you to contact me personally.',
        'Whether or not we ultimately work together, I will do my very best to help you understand your options and guide you toward the most appropriate course of action.',
        'Sometimes a single conversation can change the direction of a life.',
        'I look forward to speaking with you.',
        'Warm regards,',
      ],
    },
  ],
  signature: {
    name: 'Lowell Monkhouse',
    credentials: 'MA',
    role: 'Founder & Clinical Director',
    organisation: 'The New Practice',
  },
})
