// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.
// Source: «Final Website Instructions_DRAFT Sept 1 2026 .docx.md», lines 249–399.

import { pageSchema } from '../schemas'

export const PROCESS = pageSchema.parse({
  slug: 'our-process',
  title: 'Our Process',
  lead: 'For many people, making the first telephone call is the most difficult step in building a new life.',
  sections: [
    {
      id: 'the-new-practice-experience',
      title: 'THE NEW PRACTICE EXPERIENCE',
      paragraphs: [
        'Whether you are calling for yourself, a family member, a friend, an employee or a colleague, we understand that you may have questions, concerns, or uncertainties. You may have tried treatment before, or you may simply know that life has become increasingly difficult to manage.',
        'Our role during that first conversation is not to persuade you to enter treatment, but rather to listen.',
        'We take time to understand your circumstances, answer your questions honestly, and determine whether The New Practice is the right fit for your needs. If we believe another service would better meet your requirements, we will tell you.',
        'Every enquiry is treated privately and confidentially.',
      ],
    },
    {
      id: 'a-comprehensive-assessment',
      title: 'A Comprehensive Assessment',
      paragraphs: [
        'If you decide to proceed, the next step is a comprehensive assessment.',
        'We look beyond the immediate problem to understand the factors that may have contributed to it. This may include your trauma history, medical and psychiatric history, substance use, family relationships, physical health, nutrition, sleep, professional responsibilities, lifestyle, previous treatment experiences, and the stresses that have shaped your life.',
        'Where appropriate, members of your family and other professionals involved in your care may also contribute information that helps us develop a more complete understanding of your situation.',
        'The purpose of the assessment is not simply to identify problems. It is to understand you as a person.',
        'Only then can we design a program that reflects your individual needs.',
      ],
    },
    {
      id: 'designing-your-program',
      title: 'Designing Your Program',
      paragraphs: [
        'Following the assessment, your multidisciplinary team develops a treatment program specifically for you.',
        'Your program is built around your clinical needs, your personal goals, your family circumstances, and your responsibilities outside treatment.',
        'As your recovery progresses, your program evolves with you. Daily and sometimes hourly communication between members of your clinical team allows adjustments to be made quickly and efficiently.',
      ],
    },
    {
      id: 'arriving-at-the-new-practice',
      title: 'Arriving at The New Practice',
      paragraphs: [
        'On arrival, you will be welcomed into your private residence in Puerto Aventuras.',
        'Rather than entering a hospital or institutional setting, you will settle into a comfortable home where treatment and everyday life naturally exist together.',
        'You will be introduced to your Lead Clinician & Case Manager, who will remain your primary point of contact throughout your program, together with the other members of your multidisciplinary team.',
        'Our priority is to help you feel comfortable, establish trust, complete any remaining assessments, and allow relationships to develop naturally before the more intensive aspects of treatment begin.',
      ],
    },
    {
      id: 'why-we-have-a-lead-clinician',
      title: 'Why We Have a Lead Clinician',
      paragraphs: [
        'One of the questions we are most frequently asked is why one of our clinicians lives in the residence with you. This is one of the defining features of The New Practice.',
        'Some of the most important moments in recovery happen over breakfast, during a walk, after an emotional therapy session, while sharing dinner, or during the quiet conversations that take place at the end of the day.',
        'Your Lead Clinician becomes a consistent therapeutic presence throughout your program. They share your daily routine, eat meals with you, accompany you through the ordinary moments of each day, and are available whenever support is needed.',
        'As trust develops, conversations take place naturally. Clients often tell us that these informal moments become some of the most meaningful parts of their recovery.',
        'Your Lead Clinician is also your Case Manager.',
        'They coordinate every aspect of your program, arrange appointments, monitor your daily progress, and ensure that every member of your multidisciplinary team is working toward the same clinical objectives.',
        'Because they spend more time with you than any other member on the team, they develop a unique understanding of your evolving needs- not only during therapy sessions but throughout daily life.',
        'This continuity provides insights that simply cannot be obtained in any other way.',
      ],
    },
    {
      id: 'a-typical-day',
      title: 'A Typical Day',
      paragraphs: [
        'There is no typical day at The New Practice because every client’s program is individually designed.',
        'Begin each morning in the calm of the Caribbean with time for reflection, meditation, yoga, breathwork, or gentle movement, guided by your individual treatment plan. Breakfast is then prepared by your private chef, with each meal thoughtfully designed to support your nutritional needs, physical health, recovery, and overall wellbeing.',
        'Throughout the day you may meet with your psychiatrist, physician, psychologist, trauma therapist, addiction counsellor, nutrition specialist, family therapist, or one or more of our somatic practitioners.',
        'Your program may include cognitive behavioural therapy, EMDR, brainspotting, medical consultations, nutritional counselling, biochemical restoration, 12-step meetings, massage, yoga, mindfulness, fitness, family sessions, adult child step work or other therapeutic interventions.',
        'There are no crowded waiting rooms, institutional routines, or competing priorities. Your time belongs to you, and your program reflects your individual pace and needs.',
      ],
    },
    {
      id: 'one-team-working-together',
      title: 'One Team Working Together',
      paragraphs: [
        'Every professional involved in your care works as part of one integrated clinical team.',
        'This collaborative approach allows each discipline to build upon the work of the others. Medical care, psychiatry, psychotherapy, trauma treatment, nutritional support, somatic therapies, family work, and after care planning become part of one coordinated treatment program rather than a series of unrelated appointments.',
        'Our objective is to ensure that every member of your team is working toward one shared goal: your recovery and your new life.',
      ],
    },
    {
      id: 'family-participation',
      title: 'Family Participation',
      paragraphs: [
        'Recovery rarely affects only one person.',
        'It affects partners, parents, children, siblings, friends, and often work colleagues as well. For that reason, we encourage family participation whenever it is clinically appropriate.',
        'Our objective is not to assign blame or revisit the past unnecessarily.',
        'Every family program is individually designed to help family members understand addiction, trauma, mental health conditions and dysfunctional relationship patterns while developing healthier ways to communicate. It provides a safe environment to explore the impact these challenges have had on the family system, increase insight into behaviours like codependency, enabling and emotional dysregulation, strengthen boundaries, and promote healing for every family member.',
        'Family programs take place in Puerto Aventuras or, when clinically appropriate, in your own home or in one of our clinical residences elsewhere in the world.',
      ],
    },
    {
      id: 'preparing-to-return-home',
      title: 'Preparing to Return Home',
      paragraphs: [
        'Planning for your return home begins long before your residential program comes to an end.',
        'Together we develop an after care program that reflects your family life, professional responsibilities, support network, and long-term goals.',
        'We recognize that returning home is often one of the most challenging stages of recovery. Familiar routines, relationships, responsibilities, and environments can quickly test the progress achieved during treatment.',
        'For that reason, we believe continuity of care is essential.',
        'Whenever clinically appropriate, your Lead Clinician accompanies you home and remains with you during the early stages of your transition. They help you establish healthy routines, support you through early challenges, assist with family and workplace reintegration where appropriate, and help you apply the insights and skills developed during treatment to everyday life.',
        'This continuity allows the therapeutic relationship to continue during a period when many people are at their most vulnerable.',
      ],
    },
    {
      id: 'after-care',
      title: 'After Care',
      paragraphs: [
        'Recovery is not an event. It is an ongoing process.',
        'Following your return home, your after care program may include continuing work with your Lead Clinician in your home, secure online consultations, scheduled home visits, family therapy, collaboration with your local healthcare providers, psychiatric and medical follow-up, nutritional guidance, executive coaching, and ongoing support from members of your multidisciplinary team.',
        'The program is tailored to your circumstances and evolves as your needs change. And can be undertaken online through secure communications channels or in person or some combination of both.',
      ],
    },
    {
      id: 'treatment-without-borders',
      title: 'Treatment Without Borders',
      paragraphs: [
        'Although Puerto Aventuras provides an exceptional environment for healing, we are not defined by a location.',
        'There are times when the most appropriate place to provide treatment is within your own home or another carefully selected location elsewhere in the world. When clinically appropriate, members of The New Practice team can travel internationally to provide assessment, treatment, family work, intervention, stabilization, or after care.',
      ],
    },
    {
      id: 'nutrition-as-therapy',
      title: 'Nutrition as Therapy',
      paragraphs: [
        'Nutrition is far more than calorie intake.',
        'The food we eat influences brain function, emotional regulation, inflammation, immune function, energy, sleep, and overall health.',
        'Working closely with our Somatic Nutrition Specialist and private chef, every meal is individually prepared to support recovery and restore health. Meals are designed not only to nourish the body but also to create positive experiences around food, encourage mindful eating, and help rebuild a healthy relationship with nourishment.',
        'For clients recovering from eating disorders, addiction, trauma, or chronic stress, these everyday experiences often become an important part of the therapeutic process.',
        'When nutrition improves, sleep becomes more restorative, inflammation is reduced, and stress chemistry begins to normalize, many clients experience improved concentration, greater emotional stability, better energy, clearer thinking, and an increased capacity to benefit from psychotherapy and trauma treatment.',
      ],
    },
  ],
})
