/**
 * RESIDENCES — HAND-WRITTEN, ENTIRELY PLACEHOLDER. docs/CONTENT-GAPS.md §Residences.
 *
 * The client document supplies no residences copy. Every string below is
 * structural, prefixed `PLACEHOLDER — ` so it cannot ship unnoticed, and
 * invents no fact about the property: no room counts, no square metres, no
 * pool, no named amenities beyond what the client's own process and team
 * pages already state (a private residence, a private chef, a live-in Lead
 * Clinician, transport and security, concierge). Register follows docs/01:
 * a private house, without a name on the gate.
 *
 * Not generated by scripts/ingest-content.mjs, which never overwrites it.
 */
import { residencesPageSchema } from '../schemas'

const P = 'PLACEHOLDER — '

export const RESIDENCES = residencesPageSchema.parse({
  slug: 'residences',
  title: `${P}A private house, without a name on the gate.`,
  eyebrow: `${P}The residence`,
  lead: `${P}One client, one house, one team. Treatment and everyday life exist together here, in Puerto Aventuras, at a pace set by the person in recovery.`,
  sections: [
    {
      id: 'the-house',
      title: `${P}The house`,
      paragraphs: [
        `${P}A private clinical residence rather than an institution. The rooms are arranged for a single client and the team who live and work alongside them.`,
        `${P}Nothing on the street announces what happens inside.`,
      ],
    },
    {
      id: 'the-day',
      title: `${P}The day`,
      paragraphs: [
        `${P}Mornings begin with the sea. Meals are prepared by a private chef to the programme's nutritional plan. Sessions take place in the house, in the garden, or on the water.`,
        `${P}There are no waiting rooms and no shared schedules.`,
      ],
    },
    {
      id: 'privacy',
      title: `${P}Privacy`,
      paragraphs: [
        `${P}Puerto Aventuras is a private gated community on the Riviera Maya. The residence sits within it; access, transport and security are arranged by the practice.`,
      ],
    },
  ],
  plates: [
    { index: '01', caption: `${P}The approach`, alt: `${P}A shaded path under jungle canopy.` },
    {
      index: '02',
      caption: `${P}The terrace`,
      alt: `${P}A stone terrace opening onto still water.`,
    },
    {
      index: '03',
      caption: `${P}Linen`,
      alt: `${P}An unoccupied bed in pale linen, lit from one side.`,
    },
    {
      index: '04',
      caption: `${P}Limestone`,
      alt: `${P}A close view of a limestone wall in low sun.`,
    },
    { index: '05', caption: `${P}The water`, alt: `${P}Cenote water, clear to the stone below.` },
    {
      index: '06',
      caption: `${P}The canopy`,
      alt: `${P}Jungle canopy seen from below, after rain.`,
    },
  ],
  amenities: [
    `${P}Private residence`,
    `${P}Live-in Lead Clinician`,
    `${P}Private chef`,
    `${P}Concierge and client services`,
    `${P}Transportation and security`,
  ],
})
