/**
 * RESIDENCES — HAND-WRITTEN, ENTIRELY PLACEHOLDER. docs/CONTENT-GAPS.md §Residences.
 *
 * The client document supplies no residences copy. Every string below is
 * structural, prefixed `PLACEHOLDER — ` so it cannot ship unnoticed, and
 * states nothing the document does not: each sentence restates a line of the
 * process, about or team pages (the line is cited beside it), the plate
 * captions are neutral labels, and the amenities repeat the roles the team
 * page lists. No room, no garden, no gate, no schedule is described
 * (docs/CONTENT-PROVENANCE-AUDIT.md A21–A27). On production the route is
 * noindex and unlinked (src/lib/placeholderRoutes.ts).
 *
 * Not generated by scripts/ingest-content.mjs, which never overwrites it.
 */
import type { ResidencesPage } from '../schemas'

const P = 'PLACEHOLDER — '

export const RESIDENCES: ResidencesPage = {
  slug: 'residences',
  // l.291
  title: `${P}Your private residence in Puerto Aventuras.`,
  eyebrow: `${P}The residence`,
  // l.293
  lead: `${P}A comfortable home where treatment and everyday life naturally exist together.`,
  sections: [
    {
      id: 'the-house',
      title: `${P}The house`,
      paragraphs: [
        // l.291
        `${P}On arrival, you will be welcomed into your private residence in Puerto Aventuras.`,
        // l.303
        `${P}One of our clinicians lives in the residence with you.`,
      ],
    },
    {
      id: 'the-day',
      title: `${P}The day`,
      paragraphs: [
        // l.324
        `${P}Begin each morning in the calm of the Caribbean. Breakfast is then prepared by your private chef, with each meal designed to support your nutritional needs, physical health, recovery, and overall wellbeing.`,
        // l.330
        `${P}There are no crowded waiting rooms, institutional routines, or competing priorities.`,
      ],
    },
    {
      id: 'privacy',
      title: `${P}Privacy`,
      paragraphs: [
        // l.182
        `${P}Puerto Aventuras is a private gated community on Mexico’s Riviera Maya.`,
        // l.752, l.771–772
        `${P}Depending upon individual needs, your team may include concierge and client services, and transportation and security.`,
      ],
    },
  ],
  // Neutral labels: the frames are stock and name no part of any residence.
  // The alt text rendered for each frame is the manifest's (src/lib/residences.ts).
  plates: [
    { index: '01', caption: `${P}Plate 01`, alt: `${P}A shaded path under jungle canopy.` },
    {
      index: '02',
      caption: `${P}Plate 02`,
      alt: `${P}A stone terrace opening onto still water.`,
    },
    {
      index: '03',
      caption: `${P}Plate 03`,
      alt: `${P}An unoccupied bed in pale linen, lit from one side.`,
    },
    {
      index: '04',
      caption: `${P}Plate 04`,
      alt: `${P}A close view of a limestone wall in low sun.`,
    },
    { index: '05', caption: `${P}Plate 05`, alt: `${P}Cenote water, clear to the stone below.` },
    {
      index: '06',
      caption: `${P}Plate 06`,
      alt: `${P}Jungle canopy seen from below, after rain.`,
    },
  ],
  amenities: [
    `${P}Private residence`,
    `${P}Live-in Lead Clinician`,
    `${P}Private chef`,
    `${P}Concierge and client services`,
    `${P}Transportation and security`,
  ],
}
