/**
 * RESIDENCES — HAND-WRITTEN, ENTIRELY PLACEHOLDER. docs/CONTENT-GAPS.md §Residences.
 *
 * The client document supplies no residences copy. Every string below is
 * structural, prefixed `PLACEHOLDER — ` so it cannot ship unnoticed, and
 * states nothing the document does not: each sentence restates a line of the
 * process, about or team pages (the line is cited beside it), the plate
 * captions are neutral labels, and the amenities repeat the roles the team
 * page lists. No room, no garden, no gate, no schedule is described
 * (docs/CONTENT-PROVENANCE-AUDIT.md A21–A27). On production the route is
 * noindex and unlinked (src/lib/placeholderRoutes.ts).
 *
 * Not generated by scripts/ingest-content.mjs, which never overwrites it.
 */
import type { ResidencesPage } from '../schemas'

const P = 'PLACEHOLDER — '

export const RESIDENCES: ResidencesPage = {
  slug: 'residences',
  // l.291
  title: `${P}Your private residence in Puerto Aventuras.`,
  eyebrow: `${P}The residence`,
  // l.293
  lead: `${P}A comfortable home where treatment and everyday life naturally exist together.`,
  // Round 1 (R4d): one section of three short paragraphs where there were
  // three sections of two; the chef, the concierge and the security the
  // amenities already list are not repeated in prose.
  sections: [
    {
      id: 'the-house',
      title: `${P}The house`,
      paragraphs: [
        // l.303
        `${P}One of our clinicians lives in the residence with you.`,
        // l.324, l.330
        `${P}Begin each morning in the calm of the Caribbean. There are no crowded waiting rooms, institutional routines, or competing priorities.`,
        // l.182
        `${P}Puerto Aventuras is a private gated community on Mexico’s Riviera Maya.`,
      ],
    },
  ],
  // Neutral labels: the frames are stock and name no part of any residence.
  // The alt text rendered for each frame is the manifest's (src/lib/residences.ts).
  plates: [
    { index: '01', caption: `${P}Plate 01`, alt: `${P}A shaded path under jungle canopy.` },
    {
      index: '02',
      caption: `${P}Plate 02`,
      alt: `${P}A stone terrace opening onto still water.`,
    },
    {
      index: '03',
      caption: `${P}Plate 03`,
      alt: `${P}An unoccupied bed in pale linen, lit from one side.`,
    },
    {
      index: '04',
      caption: `${P}Plate 04`,
      alt: `${P}A close view of a limestone wall in low sun.`,
    },
    { index: '05', caption: `${P}Plate 05`, alt: `${P}Cenote water, clear to the stone below.` },
    {
      index: '06',
      caption: `${P}Plate 06`,
      alt: `${P}Jungle canopy seen from below, after rain.`,
    },
  ],
  amenities: [
    `${P}Private residence`,
    `${P}Live-in Lead Clinician`,
    `${P}Private chef`,
    `${P}Concierge and client services`,
    `${P}Transportation and security`,
  ],
}
