/**
 * Renders the ceiba mark to the small PNG the emails carry as an inline
 * (cid:) attachment, and writes it into src/server/email/mark.ts as base64.
 *
 *   node scripts/email/mark.mjs
 *
 * Email clients do not all render SVG (Gmail strips it) and the emails load
 * nothing from the network, so the mark travels inside the message. The
 * geometry is Mark.tsx's; the colours are PALETTE's (src/lib/tokens.ts):
 * canopy strokes and the brass point on a bone ground, baked in so a client
 * that darkens the message cannot lose the strokes against it. Re-run it only
 * if the mark or the palette changes.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = fileURLToPath(new URL('../../', import.meta.url))
const tokens = readFileSync(`${root}src/lib/tokens.ts`, 'utf8')
const colour = (name) => {
  const match = tokens.match(new RegExp(`\\b${name}: '(#[0-9a-f]{6})'`))
  if (!match) throw new Error(`mark.mjs: PALETTE.${name} not found in src/lib/tokens.ts`)
  return match[1]
}
const mark = readFileSync(`${root}src/components/Mark.tsx`, 'utf8')
const paths = [...mark.matchAll(/'(M 120 120 [^']+)'/g)].map((m) => m[1])
if (paths.length !== 6)
  throw new Error(`mark.mjs: expected 6 strokes in Mark.tsx, found ${paths.length}`)

/** Three times the 30px the emails display it at, so it is sharp on every screen. */
const WIDTH = 90
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="62.5 27.5 115 180" width="${WIDTH}" height="${Math.round((WIDTH * 180) / 115)}">
<rect x="62.5" y="27.5" width="115" height="180" fill="${colour('bone')}"/>
<g fill="none" stroke="${colour('canopy')}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round">
${paths.map((d) => `<path d="${d}"/>`).join('\n')}
</g>
<circle cx="120" cy="120" r="5.5" fill="${colour('brass')}"/>
</svg>`

const png = await sharp(Buffer.from(svg)).png({ compressionLevel: 9, palette: true }).toBuffer()
const meta = await sharp(png).metadata()
const out = `/**
 * GENERATED by scripts/email/mark.mjs from Mark.tsx and PALETTE. Do not edit.
 *
 * The ceiba mark as a PNG (canopy strokes, the brass point, on bone), carried
 * inside every email as an inline attachment and shown at MARK_WIDTH.
 */
export const MARK_PNG_BASE64 =
  '${png.toString('base64')}'
export const MARK_PIXEL_WIDTH = ${meta.width}
export const MARK_PIXEL_HEIGHT = ${meta.height}
`
writeFileSync(`${root}src/server/email/mark.ts`, out)
process.stdout.write(`mark.ts: ${meta.width}×${meta.height}, ${png.length} bytes\n`)
