// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.
// Source: «Final Website Instructions_DRAFT Sept 1 2026 .docx.md», lines 951–1196.
// ASSESSMENT_SERIES.supersededScale is the 0–3 scale from the how-to section; the owner chose the per-questionnaire yes/no scoring. Do not render it. See docs/CONTENT-GAPS.md.

import type { Page, AssessmentSeries, Assessment } from './schemas'

export const ASSESSMENTS_PAGE: Page = {
  slug: 'self-assessment',
  title: 'Self-Assessment',
  sections: [
    {
      id: 'understanding-yourself-is-the-first-step-toward-recovery',
      title: 'Understanding Yourself Is the First Step Toward Recovery',
      paragraphs: [
        'Many people wonder whether they have a problem long before they ask for help. They may question their relationship with alcohol, drugs, food, gambling, work, technology, or relationships. Others may recognise symptoms of anxiety, trauma, codependency, or the lasting effects of growing up in a dysfunctional family, but remain uncertain whether professional support would be beneficial.',
        'Our self-assessments have been developed to help individuals and families gain greater insight into behaviours, thoughts, and emotional patterns that may be affecting their health and wellbeing. They offer a confidential opportunity to reflect honestly on your experiences and may help you decide whether it would be beneficial to seek a professional consultation.',
      ],
    },
    {
      id: 'important-disclaimer',
      title: 'Important Disclaimer',
      paragraphs: [
        'The New Practice Self-Assessment Series is designed as a screening tool only.',
        'These questionnaires are not diagnostic instruments and should never replace a comprehensive assessment by a qualified healthcare professional.',
        'A higher score does not necessarily mean that you have a clinical disorder, and a lower score does not necessarily mean that no problem exists.',
        'If your results suggest moderate or significant concern, or if you are worried about yourself or someone you care about, we encourage you to contact The New Practice for a confidential consultation. Our experienced clinical team will help you understand your results and discuss the options most appropriate for your circumstances.',
      ],
    },
    {
      id: 'how-to-complete-the-assessment',
      title: 'How to Complete the Assessment',
      paragraphs: [
        'Answer each question as honestly as possible based on your experiences over the past twelve months.',
      ],
    },
    {
      id: 'available-self-assessments',
      title: 'Available Self-Assessments',
      paragraphs: [],
      listHeading: 'The New Practice currently offers the following confidential self-assessments:',
      list: [
        'Alcohol Addiction Self-Assessment',
        'Drug Addiction Self-Assessment',
        'Gambling Addiction Self-Assessment',
        'Food Addiction Self-Assessment',
        'Eating Disorder Screening Assessment',
        'Sex & Pornography Addiction Self-Assessment',
        'Work Addiction Self-Assessment',
        'Social Media & Technology Addiction Self-Assessment',
        'Codependency Self-Assessment',
        'Adult Children of Alcoholics & Dysfunctional Families Assessment',
      ],
    },
    {
      id: 'a-confidential-consultation',
      title: 'A Confidential Consultation',
      paragraphs: [
        'If you would like to discuss your results, or those of someone you care about, we invite you to contact The New Practice for a confidential consultation.',
        'Whether or not treatment is appropriate, we will take the time to answer your questions honestly and help you understand the options available.',
        'Sometimes the most important step toward recovery is simply reaching out.',
        'Every journey begins with a conversation.',
      ],
    },
  ],
}

export const ASSESSMENT_SERIES: AssessmentSeries = {
  toolLabel: 'Self Assessment Tool',
  seriesTitle: 'THE NEW PRACTICE™ SELF-ASSESSMENT SERIES',
  scoringText: 'Scoring: Give yourself 1 point for each “yes” answer. Total score: 0–15.',
  instruction:
    'Please answer each question honestly based on your behaviour over the past 12 months:',
  supersededScale: {
    instruction: 'Use the following scoring system:',
    scale: [
      {
        value: 0,
        label: 'Never',
      },
      {
        value: 1,
        label: 'Rarely',
      },
      {
        value: 2,
        label: 'Sometimes',
      },
      {
        value: 3,
        label: 'Frequently',
      },
    ],
    totalNote: 'Add your total score at the end of each assessment.',
    guideTitle: 'General Guide',
    guide: [
      {
        range: '0–10',
        label: 'Low Concern',
        description: 'Current responses suggest relatively few indicators of concern.',
      },
      {
        range: '11–20',
        label: 'Mild Concern',
        description:
          'Some behaviours or patterns may benefit from greater awareness or discussion.',
      },
      {
        range: '21–35',
        label: 'Moderate Concern',
        description:
          'Some behaviours or patterns may benefit from greater awareness or discussion.',
      },
      {
        range: '36 and above',
        label: 'Significant Concern',
        description:
          'Your responses indicate a high level of concern. We strongly recommend seeking a confidential professional assessment.',
      },
    ],
  },
}

export const ASSESSMENTS: readonly Assessment[] = [
  {
    slug: 'alcohol',
    order: 1,
    title: 'Alcohol Addiction Self-Assessment',
    questions: [
      'Do you often drink more alcohol than you intended?',
      'Have you tried to cut down or stop drinking but found you couldn’t?',
      'Do you spend a lot of time drinking or recovering from its effects?',
      'Do you experience strong cravings or urges to drink?',
      'Has drinking interfered with your responsibilities at work, school, or home?',
      'Do you continue drinking despite problems in relationships caused by alcohol?',
      'Have you given up activities you once enjoyed because of drinking?',
      'Do you drink in situations where it is physically dangerous?',
      'Do you continue drinking despite knowing it is harming your health?',
      'Have you developed a tolerance (needing more alcohol to feel the same effect)?',
      'Do you experience withdrawal symptoms when not drinking?',
      'Do you drink to cope with stress, anxiety, or emotions?',
      'Have others expressed concern about your drinking?',
      'Do you hide or lie about your drinking?',
      'Do you feel guilt or shame about your alcohol use?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Higher scores suggest increasing levels of problematic alcohol use. Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
  {
    slug: 'drugs',
    order: 2,
    title: 'Drug Addiction Self-Assessment',
    questions: [
      'Do you use drugs more frequently or in larger amounts than intended?',
      'Have you tried to stop or reduce use but failed?',
      'Do you spend significant time obtaining, using, or recovering from drugs?',
      'Do you experience strong cravings?',
      'Has drug use affected your responsibilities?',
      'Do you continue using despite relationship problems?',
      'Have you stopped activities due to drug use?',
      'Do you use it in risky situations?',
      'Do you continue despite physical or psychological harm?',
      'Have you developed tolerance?',
      'Do you experience withdrawal symptoms?',
      'Do you use drugs to cope emotionally?',
      'Have others expressed concern?',
      'Do you hide your use?',
      'Do you feel guilt or shame?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
  {
    slug: 'gambling',
    order: 3,
    title: 'Gambling Addiction Self-Assessment',
    questions: [
      'Do you gamble more money than you can afford to lose?',
      'Do you need to gamble with increasing amounts of money?',
      'Have you tried to stop but couldn’t?',
      'Do you feel restless or irritable when trying to cut down?',
      'Do you gamble to escape problems?',
      'Do you chase losses?',
      'Do you lie about your gambling?',
      'Has gambling harmed relationships?',
      'Has gambling affected your work or finances?',
      'Do you borrow money to gamble?',
      'Do you feel guilt or shame?',
      'Do you think about gambling constantly?',
      'Have you hidden financial losses?',
      'Do you gamble when distressed?',
      'Have others expressed concern?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
  {
    slug: 'food',
    order: 4,
    title: 'Food Addiction Self-Assessment',
    questions: [
      'Do you eat more than intended?',
      'Do you feel unable to stop eating certain foods?',
      'Do you eat when not physically hungry?',
      'Do you eat to cope with emotions?',
      'Do you feel guilt after eating?',
      'Do you hide your eating habits?',
      'Do you binge eat?',
      'Do you feel out of control around food?',
      'Have you tried to restrict but failed?',
      'Do you think about food constantly?',
      'Has eating affected your health?',
      'Do you eat rapidly?',
      'Do you eat alone due to embarrassment?',
      'Do you feel distressed about your eating?',
      'Has your weight fluctuated significantly?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
  {
    slug: 'eating-disorders',
    order: 5,
    title: 'Eating Disorder Screening Assessment',
    questions: [
      'Are you preoccupied with your weight or body shape?',
      'Do you restrict food intake?',
      'Do you binge eat?',
      'Do you purge (vomiting, laxatives, etc.)?',
      'Do you exercise excessively?',
      'Do you feel out of control when eating?',
      'Do you avoid eating in front of others?',
      'Do you feel guilt after eating?',
      'Has your weight changed significantly?',
      'Do you fear gaining weight?',
      'Do you check your body frequently?',
      'Do you compare your body to others?',
      'Has eating affected your mood?',
      'Do you feel your self-worth depends on your body?',
      'Have others expressed concern?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
  {
    slug: 'sex-and-pornography',
    order: 6,
    title: 'Sex & Pornography Addiction Self-Assessment',
    questions: [
      'Do you spend excessive time on sexual activity or pornography?',
      'Have you tried to stop but couldn’t?',
      'Do you feel out of control?',
      'Do you hide your behaviour?',
      'Has it affected relationships?',
      'Do you feel guilt or shame?',
      'Do you use it to cope emotionally?',
      'Has it interfered with responsibilities?',
      'Do you need more stimulation over time?',
      'Do you neglect other activities?',
      'Do you feel preoccupied?',
      'Do you engage in risky behaviour?',
      'Have others expressed concern?',
      'Do you feel distressed about your behaviour?',
      'Do you continue despite negative consequences?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
  {
    slug: 'work',
    order: 7,
    title: 'Work Addiction Self-Assessment',
    questions: [
      'Do you work excessively long hours?',
      'Do you feel unable to disconnect from work?',
      'Do you neglect personal relationships?',
      'Do you feel guilty when not working?',
      'Do you prioritise work over health?',
      'Do you feel anxious when not productive?',
      'Do you struggle to relax?',
      'Do you take on more than you can handle?',
      'Do you feel burned out?',
      'Do you use work to avoid emotions?',
      'Do others say you work too much?',
      'Do you feel your identity is tied to work?',
      'Do you sacrifice sleep for work?',
      'Do you feel constant pressure to achieve?',
      'Do you feel dissatisfied despite success?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
  {
    slug: 'social-media-and-technology',
    order: 8,
    title: 'Social Media & Technology Addiction Self-Assessment',
    questions: [
      'Do you spend excessive time online?',
      'Do you feel unable to reduce usage?',
      'Do you check your phone compulsively?',
      'Has it affected your sleep?',
      'Do you feel anxious without access?',
      'Do you neglect responsibilities?',
      'Do you use it to escape emotions?',
      'Do you compare yourself to others online?',
      'Do you feel worse after using it?',
      'Do you lose track of time?',
      'Do you prioritise it over relationships?',
      'Do you feel distracted constantly?',
      'Have others expressed concern?',
      'Do you feel dependent on it?',
      'Do you feel guilty about your usage?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
  {
    slug: 'codependency',
    order: 9,
    title: 'Codependency Self-Assessment',
    questions: [
      'Do you prioritise others’ needs over your own?',
      'Do you struggle to set boundaries?',
      'Do you seek approval constantly?',
      'Do you fear abandonment?',
      'Do you feel responsible for others’ emotions?',
      'Do you avoid conflict?',
      'Do you have difficulty saying no?',
      'Do you feel guilty asserting yourself?',
      'Do you stay in unhealthy relationships?',
      'Do you try to fix or rescue others?',
      'Do you neglect your own needs?',
      'Do you feel anxious when alone?',
      'Do you rely on others for self-worth?',
      'Do you feel overwhelmed by others’ problems?',
      'Do you struggle with independence?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
  {
    slug: 'adult-children',
    order: 10,
    title: 'Adult Children of Alcoholics & Dysfunctional Families Assessment',
    questions: [
      'Do you fear conflict?',
      'Are you hypervigilant?',
      'Do you struggle with trust?',
      'Do you seek perfection?',
      'Do you feel responsible for others?',
      'Do you have difficulty expressing emotions?',
      'Do you fear abandonment?',
      'Do you struggle with boundaries?',
      'Do you feel different from others?',
      'Do you avoid intimacy?',
      'Do you feel shame or guilt frequently?',
      'Do you overreact to stress?',
      'Do you struggle with self-worth?',
      'Do you repeat unhealthy relationship patterns?',
      'Do you feel emotionally disconnected?',
    ],
    scoring: {
      perYes: 1,
      max: 15,
      bands: [
        {
          key: 'mild',
          min: 0,
          max: 4,
          label: 'Mild concern',
        },
        {
          key: 'moderate',
          min: 5,
          max: 9,
          label: 'Moderate concern',
        },
        {
          key: 'severe',
          min: 10,
          max: 15,
          label: 'Severe concern',
        },
      ],
    },
    interpretation:
      'Moderate or severe scores indicate it may be helpful to seek professional support.',
  },
]
