// GENERATED by scripts/prepare-assets.mjs — do not edit by hand.
// Licence-free stock, duotoned into the brand range. Provenance and licence
// per file in design/ASSETS.md; the pipeline in docs/08-asset-pipeline.md.
export const MEDIA = {
  "hero-poster": {
    "src": "/media/hero-poster.webp",
    "width": 2400,
    "height": 1350,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoUAAsAPu1krU2ppaSiMAgBMB2JZwAAUooPHLKzdgAA9x6795i9OdUOQit3jbaYCradTZZwAAA=",
    "alt": "Sea under an overcast sky with a line of surf breaking onto a shingle beach",
    "credit": "Adrien Olichon",
    "licence": "Pexels License"
  },
  "residence-01": {
    "src": "/media/residence-01.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQBACdASoUABsAPu1gqE2ppSOiMAgBMB2JZwDGQCHfTuEf0H183pV60riAAP7YnLmqoXY7/Po2nbXJ4k72mLjPWgRy3o2lCla5+d0aCwFRHcAAAAA=",
    "alt": "Dim corridor with a louvred door open onto an empty room lit from a side window",
    "credit": "David Hernandez",
    "licence": "Pexels License"
  },
  "residence-02": {
    "src": "/media/residence-02.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQBACdASoUABsAPu1iqE2ppaOiMAgBMB2JZwC84CHaQ3gWQQ2lsolEa3UaNx8gAAD+y7Fk+RRGbaKwZKbKYfpetfIudxArujshbO3tqZyoixqj0ie4wZEAAAA=",
    "alt": "White bed linen with a band of window light across it against a dark wall",
    "credit": "Lu Pir",
    "licence": "Pexels License"
  },
  "residence-03": {
    "src": "/media/residence-03.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAwCdASoUABsAPu1osFAppaUiqAqpMB2JaQDPoBgPbqAA/thwqkbMheZfifUZoLyLhHCl/25pX9zE9clxh55MQLxx5xXUPAAAAA==",
    "alt": "Close view of pitted pale limestone",
    "credit": "Nati",
    "licence": "Pexels License"
  },
  "residence-04": {
    "src": "/media/residence-04.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACQBQCdASoUABsAPu1kqU2ppaOiMAgBMB2JZwDDNCB/9Pc6VhETO1FSWlU45aAtAzbRi7rbbAD+HQPgp+8HGqxplFwjX1SyIPSTUIO9VKU78GCaWo7Gilb21HFddgcttpA20/HdMy2N0qNsBK/fF8C7uVjYnp9kPEUBLsk6iNvlZVmVNhLadms2yPxO2UKVAAA=",
    "alt": "Dense tree canopy seen from a small terrace with a railing",
    "credit": "Maria Orlova",
    "licence": "Pexels License"
  },
  "residence-05": {
    "src": "/media/residence-05.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQBACdASoUABsAPuVepk2pJSOiMAwBIByJZwDIXCHhVtoi4UygUqHiYeiBYHXHgAD+nn/t4EpknJuwo87DscoIChVwev9cxac8ECHAAAA=",
    "alt": "Curved stone coping at the edge of dark still water reflecting trees",
    "credit": "Gökhan Yetimova",
    "licence": "Pexels License"
  },
  "residence-06": {
    "src": "/media/residence-06.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADQBACdASoUABsAPu1iqE2ppaOiMAgBMB2JZwDE2CPqU2VzaWU8urRJiO58Y915gAD9T77OENptDQnAzmtDn5eZYchL7DwkcRJYtwqFpYwN2pdC9P/8o4vHXpIY5Jj07E73UhlZWr8bMFwXNBol05QTh7pCT6DLluiLpbKhfPcR9+WMKBYrUJLpXAJ+kF3bzmK0ispzYAAAAA==",
    "alt": "Worn stone steps with leaf shadows and the shadow of a person",
    "credit": "hello aesthe",
    "licence": "Pexels License"
  },
  "index-01": {
    "src": "/media/index-01.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBQCdASoUABsAPu1kqU2ppaQiMAgBMB2JZwDKtdwAxG/PUjXJa1XniwCm/8oyd6wngAAA/swGUC9dbvUtF5B1iKciy80dFCIE6NiyCr5WNNKEszi+1FZaZeEj40dlJ94V/QYkArxPMIPrnG+J8l/NrY7N+G8ZgtUZZSd3JK1r0JSng0araPEK5iR72XkPFQdG4Ap63r8E2LgpmhgAAA==",
    "alt": "Tree canopy seen from below against a white sky",
    "credit": "Lino Mohandas",
    "licence": "Pexels License"
  },
  "index-02": {
    "src": "/media/index-02.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwBACdASoUABsAPu1oqU2ppqOiMAgBMB2JZwC/7CHfq2+29fPHZCtgHgwmAAD+rl6LnieVCLKfhYP91sE9RvUKpRx37Ze/oUMW1eXBD3Zn1QAA",
    "alt": "Sea swell under a flat grey sky",
    "credit": "Josh Amparan",
    "licence": "Pexels License"
  },
  "index-03": {
    "src": "/media/index-03.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQBACdASoUABsAPu1srVEppiQiqAqpMB2JZwDM0BEczFI3ppCaFZiHwubAAP7jBVsY+Pn0t4Z4ZQbZrWXkN9ib7pbTHnj4vFW1adDITA5PHoMBaPyAAAAA",
    "alt": "Close view of dark fissured limestone",
    "credit": "cottonbro studio",
    "licence": "Pexels License"
  },
  "index-04": {
    "src": "/media/index-04.webp",
    "width": 1040,
    "height": 1387,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQBACdASoUABsAPu1iq1AppSOjMBgIATAdiWcAyngQ3k3dTGgqW5gT5m7YsgAA/m8tsDk+neYpI2xZchJZcJa1nW94t3ELutSFDbe2vUsx9VBDxRoQywlo3mttIMBcnrh0gAAA",
    "alt": "Broad palm leaves beaded with rain",
    "credit": "Deeana Arts",
    "licence": "Pexels License"
  },
  "band-discretion": {
    "src": "/media/band-discretion.webp",
    "width": 2100,
    "height": 900,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAwCdASoUAAkAPu1kqU2ppaQiMAgBMB2JZwDImB4eAEfgmQwAAP7CcwS39RfMQH/lM0zyDF5kbkUN7qj7L5K7Z+tXI+Vrk0IAAA==",
    "alt": "A person seen from behind standing at a window with a palm shadow on the blind",
    "credit": "Wavy. revolution",
    "licence": "Pexels License"
  },
  "hero-surf-poster": {
    "src": "/media/hero-surf-poster.webp",
    "width": 2400,
    "height": 1350,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAwCdASoUAAsAPu1iqk2ppaQiMAgBMB2JZwDA3B0h/CT5aOCAAOzvupiMFAnt0YbBjd6sCKSUX0AAAAA=",
    "alt": "Poster frame: Surf washing over a shingle shore under an overcast sky",
    "credit": "Engin Akyurt",
    "licence": "Pexels License"
  },
  "hero-canopy-poster": {
    "src": "/media/hero-canopy-poster.webp",
    "width": 2400,
    "height": 1350,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JZwDG9BxIp/DLvO9/UKMB0AAA/R2hg29cgVnTDSduG6hr64JjhIjEc5ppir8vCMtzwAAA",
    "alt": "Poster frame: Broad leaves in a misty jungle understory",
    "credit": "Florian Delée",
    "licence": "Pexels License"
  },
  "hero-cenote-poster": {
    "src": "/media/hero-cenote-poster.webp",
    "width": 2400,
    "height": 1350,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZwAAXjQXkVomiXQkrAAA/stmZjBCEcnJh/s57ITPrnpc+ozIKnjHer77bBbNqJi7zMunJWoAAA==",
    "alt": "Poster frame: Still water and stalactites inside a limestone cave lit by a single light",
    "credit": "Florian Delée",
    "licence": "Pexels License"
  }
} as const

export type MediaKey = keyof typeof MEDIA
export type MediaEntry = (typeof MEDIA)[MediaKey]

/** Hero and full-bleed loops. `poster` is a MediaKey; the poster is the LCP. */
export const VIDEO = {
  "hero-surf": {
    "mp4": "/video/hero-surf.mp4",
    "webm": "/video/hero-surf.webm",
    "poster": "hero-surf-poster",
    "width": 1920,
    "height": 1080,
    "seconds": 12,
    "alt": "Surf washing over a shingle shore under an overcast sky",
    "credit": "Engin Akyurt",
    "licence": "Pexels License"
  },
  "hero-canopy": {
    "mp4": "/video/hero-canopy.mp4",
    "webm": "/video/hero-canopy.webm",
    "poster": "hero-canopy-poster",
    "width": 1920,
    "height": 1080,
    "seconds": 12,
    "alt": "Broad leaves in a misty jungle understory",
    "credit": "Florian Delée",
    "licence": "Pexels License"
  },
  "hero-cenote": {
    "mp4": "/video/hero-cenote.mp4",
    "webm": "/video/hero-cenote.webm",
    "poster": "hero-cenote-poster",
    "width": 1920,
    "height": 1080,
    "seconds": 12,
    "alt": "Still water and stalactites inside a limestone cave lit by a single light",
    "credit": "Florian Delée",
    "licence": "Pexels License"
  }
} as const

export type VideoKey = keyof typeof VIDEO
