// GENERATED by scripts/prepare-assets.mjs — do not edit by hand.
//
// STUB. No media has been prepared yet: the demo's plates were placeholders
// and were deliberately not carried over. Task 2b runs `npm run assets` against
// design/media.manifest.json and overwrites this file with the real manifest,
// which is an `as const` object keyed by frame name. Until then the map is
// empty and typed loosely so <Plate> compiles; it throws on an unknown key.
export type MediaEntry = {
  src: string
  width: number
  height: number
  blurDataURL: string
}

export const MEDIA: Readonly<Record<string, MediaEntry>> = {}

export type MediaKey = keyof typeof MEDIA
