// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.
// Source: «Final Website Instructions_DRAFT Sept 1 2026 .docx.md», lines 401–718.

import { z } from 'zod'
import { pageSchema, serviceSchema } from './schemas'

export const SERVICES_PAGE = pageSchema.parse({
  slug: 'clinical-services',
  title: 'Clinical Services',
  sections: [
    {
      id: 'individualized-treatment-for-complex-human-problems',
      title: 'Individualized Treatment for Complex Human Problems',
      paragraphs: [
        'No two people arrive at The New Practice with exactly the same history.',
        'Even when two clients share the same diagnosis, the factors that contributed to their difficulties, their strengths, family circumstances, physical health and personal goals are never identical.',
        'For that reason, our clients receive a comprehensive assessment followed by a treatment plan designed specifically for their needs. Our multidisciplinary team works together throughout their program, ensuring that every aspect of treatment is coordinated and responsive as recovery progresses.',
        'Treatment may include one or more of the following clinical services.',
      ],
    },
  ],
})

export const SERVICES = z.array(serviceSchema).parse([
  {
    slug: 'addiction-treatment',
    order: 1,
    title: 'Addiction Treatment',
    intro: [
      'We understand addiction as a complex condition influenced by biology, trauma, family systems, life experiences, and environmental factors.',
      'Our goal is not simply to stop the use of alcohol or drugs. We aim to understand why addiction developed and to help each client build a life that no longer depends upon alcohol, drugs, or other compulsive behaviours to cope with emotional pain.',
    ],
    treatsHeading: 'We provide individualized treatment for people experiencing problems with:',
    treats: [
      'Alcohol',
      'Cocaine',
      'Prescription medications',
      'Opioids',
      'Cannabis',
      'Methamphetamine',
      'Gambling',
      'Sex and pornography',
      'Compulsive sexual behaviour',
      'Internet and technology addiction',
      'Food addiction',
      'Work addiction',
      'Process addictions',
      'Multiple addictions',
      'Codependency',
    ],
    mayIncludeHeading: 'Treatment may include:',
    mayInclude: [
      'Comprehensive assessment',
      'Medically supervised detoxification where required',
      '12-Step facilitation and meetings',
      'Individual psychotherapy',
      'Trauma therapy',
      'Relapse prevention',
      'Recovery education',
      'Family program',
      'Biochemical restoration',
      'Lifestyle redesign',
      'After care',
    ],
    outro: [
      'Many clients also experience anxiety, depression, trauma, or relationship difficulties alongside addiction. Our treatment addresses these issues together rather than in isolation.',
    ],
  },
  {
    slug: 'trauma-and-complex-trauma',
    order: 2,
    title: 'Trauma & Complex Trauma',
    intro: [
      'Many people we work with have experienced overwhelming or traumatic life events that continue to affect their emotional wellbeing, relationships, physical health, and ability to function.',
    ],
    treatsHeading: 'We provide treatment for:',
    treats: [
      'Acute trauma',
      'Complex trauma (Complex PTSD)',
      'Post-Traumatic Stress Disorder (PTSD)',
      'Developmental trauma',
      'Childhood emotional neglect',
      'Childhood abuse',
      'Attachment trauma',
      'Narcissistic abuse',
      'Emotional abuse',
      'Chronic stress',
      'Nervous system dysregulation',
      'Grief and complicated bereavement',
    ],
    outro: [
      'Trauma can affect memory, relationships, emotional regulation, sleep, physical health, behaviour, and the way the nervous system responds to perceived danger. For some clients it follows a single overwhelming event, for others it develops through childhood adversity; neglect, abuse, attachment disruption, repeated loss, coercive relationships, chronic stress, or prolonged exposure to situations in which the person did not feel safe.',
    ],
    subsections: [
      {
        id: 'trauma-focused-treatment-may-include',
        title: 'Trauma-Focused Treatment May Include…',
        paragraphs: [],
        definitions: [
          {
            term: 'EMDR (Eye Movement Desensitization and Reprocessing)',
            description:
              'a structured trauma therapy used to help clients process distressing memories and reduce the intensity of the thoughts, emotions, images, and bodily responses associated with them.',
          },
          {
            term: 'Brainspotting',
            description:
              'a focused therapeutic approach that uses visual attention and body awareness to help clients access and process emotionally charged experiences. It may be used selectively where clinically appropriate and is integrated within the wider treatment plan.',
          },
          {
            term: 'Somatic Experiencing and Nervous System Regulation',
            description:
              'body-based work designed to help clients notice and regulate physiological responses to stress and trauma. This can include breathwork, movement, therapeutic bodywork, mindfulness, trauma-informed yoga, grounding, and other somatic interventions.',
          },
          {
            term: 'Internal Family Systems (IFS) and Parts-Informed Work',
            description:
              'helps clients understand protective, vulnerable, and conflicted parts of themselves with greater curiosity and compassion, particularly where trauma has created persistent patterns of shame, avoidance, self-criticism, or emotional reactivity.',
          },
          {
            term: 'Attachment-Focused and Relational Psychotherapy',
            description:
              'treatment that examines how early relationships and later interpersonal experiences may influence trust, boundaries, intimacy, conflict, abandonment fears, and the ability to feel safe with other people.',
          },
          {
            term: 'Trauma-Focused Cognitive and Behavioural Approaches',
            description:
              'where appropriate, clinicians may use established cognitive and behavioural methods to address trauma-related beliefs, avoidance, fear responses, and patterns that continue to interfere with daily life.',
          },
          {
            term: 'Mindfulness, Grounding and Stabilization',
            description:
              'practical methods that help clients remain present, recognize activation earlier, develop emotional regulation, and build the capacity required for deeper trauma processing.',
          },
          {
            term: 'Inner Child and Developmental Trauma Work',
            description:
              'for clients whose current difficulties are connected to childhood experiences, treatment may include carefully structured work focused on unmet developmental needs, protective adaptations, self-compassion, boundaries, and reparenting. The objective is not to make a client repeatedly relive traumatic events. It is to help the brain, body, and nervous system process experiences that continue to feel present, reduce their power over current life, and build a greater capacity for safety and emotional resilience.',
          },
        ],
      },
    ],
  },
  {
    slug: 'mental-health',
    order: 3,
    title: 'Mental Health',
    intro: [
      'We provide individualized treatment for adults experiencing depression, anxiety, chronic stress, burnout, emotional dysregulation, mood disorders, grief, and other psychological difficulties.',
      'Rather than focusing exclusively on symptoms or a psychiatric diagnosis, we identify the underlying cause. Treatment will include a psychiatric assessment and treatment planning, psychotherapy, trauma treatment, stress management, biochemical restoration, medication (only as a last resort), and after care.',
    ],
    treatsHeading:
      'We work with adults experiencing a wide range of emotional and psychological difficulties, including:',
    treats: [
      'Depression',
      'Anxiety disorders',
      'Panic attacks',
      'Burnout',
      'Mood disorders',
      'Bipolar disorder',
      'Obsessive Compulsive Disorder (OCD)',
      'Attention Deficit Hyperactivity Disorder (ADHD)',
      'Emotional dysregulation',
      'Sleep disorders',
      'Stress-related disorders',
      'Adjustment disorders',
      'Low self-esteem',
      'Perfectionism',
      'Social isolation',
    ],
  },
  {
    slug: 'eating-disorders',
    order: 4,
    title: 'Eating Disorders',
    intro: [
      'Eating disorders are rarely about food alone. They often reflect deeper struggles involving emotional regulation, trauma, perfectionism, self-esteem, anxiety, control and relationships.',
      'Our multidisciplinary approach integrates medical oversight, nutritional rehabilitation, psychotherapy, trauma treatment, biochemical restoration, family work, and nervous system regulation.',
    ],
    treatsHeading: 'We provide comprehensive care for individuals experiencing:',
    treats: [
      'Anorexia nervosa',
      'Bulimia nervosa',
      'Binge Eating Disorder',
      'Avoidant/Restrictive Food Intake Disorder (ARFID)',
      'Compulsive exercise',
      'Body image disturbance',
      'Chronic dieting',
      'Emotional eating',
      'Eating disorders associated with trauma',
    ],
  },
  {
    slug: 'executive-health-and-burnout',
    order: 5,
    title: 'Executive Health & Burnout',
    intro: [
      'Chronic pressure, long working hours, constant decision-making and the expectations associated with leadership can gradually affect physical health, emotional wellbeing, family relationships, and performance.',
      'Our Executive Health program helps individuals recover from burnout, chronic stress, anxiety, emotional exhaustion, and destructive coping strategies while supporting a healthier and more sustainable way of living and leading.',
      'Many of our clients are business leaders, entrepreneurs, professionals, physicians, lawyers, family business owners, athletes, artists, and public figures whose responsibilities create exceptional demands.',
    ],
    treatsHeading: 'We frequently work with individuals experiencing:',
    treats: [
      'Executive burnout',
      'Chronic occupational stress',
      'Decision fatigue',
      'Emotional exhaustion',
      'Sleep disruption',
      'Alcohol or substance misuse',
      'Relationship strain',
      'Loss of purpose',
      'Work-life imbalance',
      'Leadership stress',
      'Performance anxiety',
    ],
    outro: [
      'Burnout is far more than feeling tired. It’s a state of physical, emotional, and psychological exhaustion that often develops after prolonged periods of chronic stress.',
    ],
  },
  {
    slug: 'biochemical-restoration',
    order: 6,
    title: 'Biochemical Restoration',
    intro: [
      'Biochemical Restoration is one component of our integrative approach to healing. It is based on the understanding that emotional wellbeing, mental clarity, physical health, nutrition, sleep, stress, hormones, gut health, inflammation, and nervous system function are closely interconnected. When the body is out of balance, psychological recovery is often more difficult. By restoring physical health, we create the conditions that support lasting emotional and psychological healing.',
      'We seek to understand the biological factors that may be contributing to anxiety, depression, fatigue, cognitive difficulties, addiction, eating disorders, and other mental health challenges. Our emphasis is on restoring optimal health through nutrition, targeted supplementation, lifestyle changes, sleep optimization, exercise, stress reduction, and, when appropriate, medical interventions.',
      'Our goal is simple: to optimize the body’s natural capacity to heal so that clients have the physical resilience, emotional stability, and mental clarity necessary to fully engage in the therapeutic process and sustain long-term recovery.',
    ],
  },
  {
    slug: 'somatic-therapies-and-nervous-system-regulation',
    order: 7,
    title: 'Somatic Therapies & Nervous System Regulation',
    intro: [
      'Trauma and chronic stress affect both the mind and the body.',
      'For many people, healing requires more than talking. Body-centred therapies can help regulate the nervous system, reduce chronic stress, improve emotional awareness, and support recovery from trauma.',
      'Depending on your individual program, treatment may include breathwork, therapeutic bodywork, yoga, mindfulness, movement therapies, massage, relaxation techniques, and other somatic interventions designed to complement trauma work and cognitive/talk therapy.',
    ],
  },
  {
    slug: 'inner-child-work',
    order: 8,
    title: 'Inner Child Work',
    intro: [
      'For some clients, the difficulties they experience in adult life are rooted in adaptations developed much earlier. Growing up in alcoholic or otherwise addicted homes, homes affected by mental illness, or environments involving emotional neglect, abandonment, instability, chronic conflict, sexual abuse, physical abuse or other forms of trauma can profoundly influence how a child learns to survive, protect themselves and relate to other people.',
      'These adaptations may have been necessary in childhood, but later appear as people-pleasing, perfectionism, hypervigilance, emotional suppression, difficulty trusting, fear of abandonment, poor boundaries, compulsive behaviour, codependency or a need to control.',
      'Inner Child Work at The New Practice helps clients understand the connection between these early experiences and the reactions that continue to affect their lives today. The purpose is not to remain focused on the past or to assign blame. It is to understand what happened, how the client adapted, and whether those adaptations are still serving them.',
    ],
    subsections: [
      {
        id: 'how-it-works',
        title: 'How It Works',
        paragraphs: [
          'Working at a pace appropriate to the individual, the client learns to recognise when a present-day situation is activating an earlier emotional wound. A disagreement, criticism, rejection, intimacy, conflict or fear of losing someone, for example, may trigger an emotional response that belongs as much to the past as it does to the present.',
          'The client begins to identify the younger, vulnerable parts of themselves and beliefs that may have developed during childhood.',
          'The work then moves beyond insight to reparenting. The adult client learns to provide themselves with the reassurance, protection, compassion, boundaries and emotional security that may have been absent during childhood.',
          'Rather than asking, “What is wrong with me?”, the client begins asking, “What was this behaviour trying to protect me from, and what do I need now?”',
          'At The New Practice, Inner Child Work can be integrated with trauma therapy, EMDR, somatic work, breathwork and other therapeutic approaches.',
        ],
      },
      {
        id: 'the-benefits',
        title: 'The Benefits',
        paragraphs: [],
        listHeading: 'Over time, Inner Child Work can help clients develop:',
        list: [
          'Greater emotional awareness and self-compassion',
          'Reduced shame and self-criticism',
          'Healthier boundaries',
          'Less sensitivity to rejection and abandonment',
          'Greater ability to tolerate conflict and uncertainty',
          'Reduced compulsive and self-protective behaviours',
          'Healthier relationships and attachment',
          'Greater trust in themselves and their own needs',
          'An increased ability to respond to life from the resources of the adult self rather than the fears and survival strategies developed in childhood',
        ],
      },
    ],
  },
  {
    slug: 'recovery-management-and-after-care',
    order: 9,
    title: 'Recovery Management & After care',
    intro: [
      'Treatment is only one stage of recovery. The transition home often determines whether progress made during treatment becomes a lasting change.',
      'For this reason, after care begins before your residential program ends.',
      'Whenever clinically appropriate, your Lead Clinician accompanies you home and helps establish healthy routines, navigate early challenges, support family reintegration, and translate therapeutic progress into everyday life.',
      'Your after care program may also include online consultations, home visits, family therapy, psychiatric follow-up, executive coaching, collaboration with local professionals, and ongoing support from members of The New Practice team.',
    ],
    subsections: [
      {
        id: 'after-care-needs',
        title: 'After care needs',
        paragraphs: [],
        listHeading:
          'Our after care program can provide ongoing clinical support for people who require:',
        list: [
          'Recovery management',
          'Relapse prevention',
          'Therapeutic support',
          'Family consultation',
          'Psychiatric follow-up',
          'Lifestyle restructuring',
          'Executive support',
          'Long-term accountability',
          'Home-based treatment',
          'International clinical support',
        ],
      },
    ],
  },
  {
    slug: 'interventions-and-crisis-response',
    order: 10,
    title: 'Interventions & Crisis Response',
    intro: [
      'Families often contact us at a time of crisis. A loved one may be refusing treatment, experiencing a psychiatric emergency, actively using alcohol or drugs, suffering from an eating disorder, or placing themselves or others at risk. Relationships may have deteriorated, trust may have been lost, and family members often feel frightened, exhausted, and uncertain about what to do next.',
      'Our approach begins with understanding the individual, the family, and the circumstances leading to the crisis.',
      'We conduct a comprehensive assessment before recommending a course of action. We speak with family members, physicians, therapists, lawyers, family office representatives, and other professionals where appropriate. Our objective is to understand not only the immediate problem, but also the biological, psychological, family, medical, occupational, and environmental factors contributing to the current situation.',
      'Following this assessment we develop an intervention strategy tailored to the individual and their family.',
      'In some cases this may involve a carefully planned formal intervention. In others, a series of structured conversations over several days may prove more effective than a single intervention meeting. Every situation is different and our recommendations are guided by clinical judgement rather than a predetermined model.',
      'When treatment is accepted, we coordinate every aspect of the admission process. This may include medical assessment, psychiatric consultation, transportation, travel arrangements, legal or security considerations, family support, and the immediate implementation of a personalized treatment program.',
    ],
  },
  {
    slug: 'family-program',
    order: 11,
    title: 'Family Program',
    intro: [
      'Recovery is most successful when families understand the challenges they are facing and learn healthier ways of supporting one another.',
      'Every Family program is individually designed to help family members understand addiction, trauma, mental health conditions and dysfunctional relationship patterns while developing healthier ways to communicate, support recovery and care for themselves. It provides a safe environment to explore the impact these challenges have had on the family system, increase insight into behaviours like codependency, enabling and emotional dysregulation, strengthen boundaries, and promote healing for every family member.',
    ],
    treatsHeading: 'We work with individuals, couples, and families experiencing:',
    treats: [
      'Codependency',
      'Enabling behaviours',
      'Family conflict',
      'Marital and relationship difficulties',
      'Separation and divorce',
      'Communication problems',
      'Boundary difficulties',
      'Recovery from narcissistic relationships',
      'Trauma bonding',
      'Adult Children of Dysfunctional Families',
      'Parenting challenges',
      'Intergenerational trauma',
    ],
    outro: [
      'For that reason, we believe lasting recovery is most successful when those closest to the client are given the opportunity to understand what has happened, learn healthier ways of relating to one another, and become active participants in the recovery process.',
      'Recovery is rarely an individual journey.',
      'It is often a family journey.',
    ],
  },
])
