// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.
// Source: «Final Website Instructions_DRAFT Sept 1 2026 .docx.md», lines 720–949.

import type { Page, TeamMember } from './schemas'

export const TEAM_PAGE: Page = {
  slug: 'team',
  title: 'Team',
  sections: [
    {
      id: 'intro',
      paragraphs: [
        'The quality of any treatment program is ultimately determined by the quality of the people delivering it.',
        'At The New Practice, every client is supported by a multidisciplinary team assembled specifically for their individual needs. Unlike traditional treatment centres, where clinicians divide their time among many clients, our professionals work together with one shared purpose: helping one individual and their family achieve lasting recovery.',
        'Psychiatrists, psychologists, physicians, trauma therapists, addiction counselors, family therapists, nutritional specialists, somatic practitioners, and wellness professionals work as one integrated clinical team. Every discipline contributes its expertise while remaining focused on the same treatment goals.',
      ],
    },
    {
      id: 'one-client-one-team',
      title: 'One Client. One Team.',
      paragraphs: [],
      subsections: [
        {
          id: 'the-clinical-director',
          title: 'The Clinical Director',
          paragraphs: [
            'Every program is led by the Clinical Director, who oversees the assessment, development, and implementation of each client’s treatment plan.',
            'Working closely with the Lead Clinician and the multidisciplinary team, the Clinical Director reviews progress continuously, coordinates clinical decision-making, and ensures that treatment remains responsive to the client’s changing needs throughout the program.',
          ],
        },
        {
          id: 'the-lead-clinician-and-case-manager',
          title: 'The Lead Clinician & Case Manager',
          paragraphs: [
            'One of the defining features of The New Practice is the role of the Lead Clinician.',
            'The Lead Clinician lives alongside the client throughout the residential program and serves as the client’s primary therapeutic contact, case manager, and clinical coordinator. They coordinate daily activities, maintain continuous communication with the Clinical Director and the multidisciplinary team, support the client between appointments, and help integrate therapeutic work into everyday life.',
            'Whenever clinically appropriate, the Lead Clinician also accompanies the client home following residential treatment, providing continuity during one of the most important stages of recovery.',
            'We believe that maintaining a consistent therapeutic relationship before, during, and after treatment significantly improves the likelihood of long-term success.',
          ],
        },
        {
          id: 'a-multidisciplinary-team',
          title: 'A Multidisciplinary Team',
          paragraphs: [],
          listHeading: 'Depending upon individual needs, your team may include:',
          list: [
            'Clinical Director',
            'Lead Clinician & Case Manager',
            'Psychiatrist',
            'Physician',
            'Psychologist',
            'Addiction Counsellor',
            'Trauma Therapist',
            'Family Therapist',
            'EMDR Therapist',
            'Brainspotting Practitioner',
            'Somatic Therapist',
            'Bodywork Specialist',
            'Nutrition Specialist',
            'Private Chef',
            'Biochemical Restoration Specialist',
            'Executive Coach',
            'Recovery Management Specialist',
            'Wellness Practitioner',
            'Concierge & Client Services',
            'Transportation & Security',
          ],
          outro: [
            'We look for clinicians who combine knowledge with humility, compassion, curiosity, integrity, and genuine respect for the people they serve.',
            'Recovery depends upon relationships. For that reason, we believe our greatest strength is not simply the experience of each individual professional, but the way our team works together in support of every client and family entrusted to our care.',
          ],
        },
      ],
    },
  ],
}

export const TEAM: readonly TeamMember[] = [
  {
    slug: 'lowell-monkhouse',
    order: 1,
    name: 'Lowell Monkhouse',
    credentials: 'MA',
    role: 'Founder and Clinical Director',
    paragraphs: [
      'Lowell Monkhouse is the Founder and Clinical Director of The New Practice. For more than twenty years he has worked with individuals, families, executives, entrepreneurs, and ultra-high-net-worth clients affected by addiction, trauma, eating disorders, and complex mental health challenges.',
      'A graduate of the Hazelden Betty Ford Graduate School of Addiction Studies and has dedicated his professional life to advancing individualized treatment, trauma recovery, family systems therapy, and long-term recovery management.',
      'Before entering behavioural healthcare, Lowell worked in education, Canadian politics and public affairs consulting. Drawn by a desire to help individuals and families affected by addiction, he returned to university and began what would become a lifelong career in private behavioural healthcare.',
      'Throughout his career he has worked with some of the most respected treatment organisations in North America and Europe, including Hazelden in Center City, Minnesota, The Priory in London, Promis Clinics in Europe, and Clinique Les Alpes in Switzerland.',
      'In 2007 Lowell founded The Kusnacht Practice in Küsnacht, Switzerland, where he developed the first bespoke model of behavioural healthcare for very wealthy and high-profile individuals.',
      'Following the sale of his interests in The Kusnacht Practice, Lowell returned to Canada, where he became involved in the development and management of treatment facilities, business ventures, and real estate projects. In 2025 he relocated to Mexico to establish The New Practice, bringing together everything he had learned from more than two decades working with clients and families around the world.',
    ],
  },
  {
    slug: 'nathaniel-bruce',
    order: 2,
    name: 'Nathaniel Bruce',
    role: 'Chief Operating Officer',
    paragraphs: [
      'Nathaniel Bruce brings a strong combination of business leadership, hospitality management, financial oversight, team development and international experience to his role as Chief Operating Officer at The New Practice.',
      'Nathaniel was previously based in Western Canada, where he founded and ran a high-volume automotive business, led a team while growing annual revenue to more than $15 million. He oversaw strategy, financial relationships, team performance and operating systems.',
      'As Chief Operating Officer, Nathaniel oversees the operational, hospitality, logistical and client-service functions of The New Practice. Working alongside the Clinical Director and multidisciplinary team, he helps ensure that every aspect of the client’s environment is delivered with the privacy, responsiveness, organization and exceptional standards central to the Practice’s one-client model.',
    ],
  },
  {
    slug: 'elena-vasquez-whitfield',
    order: 3,
    name: 'Dr. Elena Vasquez-Whitfield',
    credentials: 'M.D.',
    role: 'Consulting Psychiatrist',
    paragraphs: [
      'Dr. Vasquez-Whitfield earned her medical degree from the Universidad Autónoma de Madrid before completing her psychiatric residency at Johns Hopkins Hospital, followed by a fellowship in addiction psychiatry at the Yale School of Medicine.',
      'Over the past eighteen years, she has worked across three continents; beginning at a public mental health clinic in Bogotá, then leading a dual-diagnosis unit in Zurich, before joining private practice. She is board-certified in both general and addiction psychiatry and has published on trauma-informed approaches to treating substance use disorders. She is fluent in Spanish, English, and Portuguese, and conversational in German.',
    ],
  },
  {
    slug: 'justin-nolan',
    order: 4,
    name: 'Justin Nolan',
    role: 'Director of Business Development & Strategic Partnerships',
    paragraphs: [
      'Justin Nolan serves as Director of Business Development & Strategic Partnerships at The New Practice, where he is responsible for developing strategic referral relationships, overseeing admissions, and expanding the organisation’s international professional network.',
      'With more than 20 years of experience across business development, addiction recovery, mental health, leadership, and client engagement, Justin has built an international reputation for creating trusted relationships with healthcare professionals, interventionists, treatment providers, private family offices, and referral partners. His approach is founded on authenticity, discretion, and a deep understanding that successful treatment begins long before a client enters a program.',
      'As former Director and Program Lead of 21Renew Wellness Retreats, operating across Australia and Bali, Justin led admissions, business development, strategic partnerships, interventions, operational management, and referral network development. Working closely with individuals, families, clinicians, and allied professionals, he helped guide clients through complex addiction, trauma, and mental health challenges while establishing enduring professional relationships throughout the recovery community.',
      'Justin later founded Malaya Care Support Network, providing recovery-focused mental health and psychosocial support services for clients connected with Forensicare and Thomas Embling Hospital. This work further strengthened his expertise in stakeholder engagement, long-term recovery planning, and supporting individuals with complex mental health needs.',
      'At The New Practice, Justin works closely with referring clinicians, interventionists, healthcare professionals, and families worldwide, ensuring every prospective client experiences confidence, discretion, and personalised support from their very first contact. His leadership plays a key role in expanding The New Practice’s international referral network while maintaining the exceptional standards of care and service on which the organisation is built.',
    ],
  },
  {
    slug: 'iona-hames',
    order: 5,
    name: 'Iona Hames',
    role: 'Marketing & Client Services Consultant',
    paragraphs: [
      'Iona Hames brings a distinctive combination of experience in private behavioural healthcare, international client relations, business development, marketing and reputation management to The New Practice.',
      'Over nearly eight years in the addiction and mental health treatment sector, Iona has worked closely with clients, families, clinicians, professional referrers and international treatment providers. Her experience includes complex international admissions, interventions, cross-border case coordination and the development of trusted relationships with individuals and families seeking highly private and personalised care.',
      'Iona previously held two senior positions at The Kusnacht Practice in Switzerland, initially as Client and Business Relations Manager and subsequently as Head of Business Development. There, she managed relationships with an international clientele that included VVIP individuals and families, coordinated complex admissions and interventions, and developed relationships with leading healthcare professionals and referral partners around the world.',
      'More recently, Iona has held senior leadership and international relations roles within specialist treatment organisations in Switzerland and the Netherlands. Her work has included supporting international families considering treatment, developing referral relationships, coordinating international admissions and advising senior leadership on communications, positioning and strategic growth.',
      'Before entering behavioural healthcare, Iona spent more than two decades in senior communications, public relations and brand leadership across luxury fashion and the international music industry. She established and ran her own communications consultancy, served as Head of Public Relations for Jaeger and spent eight years at EMI Music, where she led international publicity campaigns and managed high-profile reputation and communications issues.',
      'At The New Practice, Iona has responsibility for marketing, international relationships and the client experience surrounding treatment. She is often part of the relationship with a prospective client, their family or professional referrer from the earliest conversations, helping them understand whether The New Practice is the right environment and ensuring that the process of entering treatment is handled with discretion, sensitivity and exceptional personal attention',
    ],
  },
  {
    slug: 'richard-warren',
    order: 6,
    name: 'Richard Warren',
    role: 'Director of Operations, Security & Client Services',
    paragraphs: [
      'Richard Warren oversees operations, transportation, logistics, security, concierge services, and client support at The New Practice. Working closely with both the Clinical Director and Lead Clinician, he helps ensure that every aspect of the client’s experience is delivered safely, discreetly, and with exceptional attention to detail.',
      'Richard brings an unusually broad entrepreneurial background to the practice. Throughout his career he has owned and managed businesses within the music industry, entertainment, hospitality, manufacturing, event production, luxury concierge services, and private security.',
      'He founded an independent record label that was subsequently acquired by Sony Music, managed photographic studios in London, operated manufacturing businesses, and later established successful event production and sound companies in Ibiza and Tulum. Most recently he developed a concierge, transportation, event production, and security company in Mexico serving affluent international clients, executives, and private families.',
      'His experience supporting high-profile individuals has given him a practical understanding of discretion, logistics, crisis management, and client care in demanding environments.',
      'Richard also brings the perspective of long-term personal recovery. His own experience enables him to appreciate the challenges clients and families face while recognising that recovery extends far beyond formal therapy sessions.',
      'At The New Practice, Richard believes that every interaction contributes to a client’s sense of safety, trust, and wellbeing. Whether coordinating international travel, supporting family members, arranging security, or simply helping clients navigate daily life, he sees operational excellence as an important part of the therapeutic experience.',
    ],
  },
  {
    slug: 'patricia-heyland',
    order: 7,
    name: 'Patricia Heyland',
    credentials: 'MSc',
    role: 'Chief Trauma Therapist & Senior Addiction Counsellor',
    paragraphs: [
      'Patricia Heyland is an Integrative Psychotherapist with almost thirty years of clinical experience specialising in trauma, addiction, eating disorders, and complex PTSD.',
      'As Chief Trauma Therapist and Senior Addiction Counsellor at The New Practice, Patricia works with individuals whose lives have been affected by developmental trauma, attachment injuries, substance use disorders, emotional dysregulation, and complex psychological difficulties. Her approach combines clinical expertise with warmth, compassion, and a deep respect for each client’s individual journey.',
      'Patricia holds a Master of Science in Addiction Psychology and Counselling from the University of Greenwich, together with postgraduate qualifications in Humanistic Counselling and Psychotherapy and Eating Disorder Skills.',
      'Her work integrates a range of evidence-based trauma therapies, including EMDR, Somatic Experiencing®, Internal Family Systems (IFS), Brainspotting, and Emotional Freedom Techniques (EFT). Since 2007 she has worked within leading psychiatric and addiction treatment settings in both the United Kingdom and Switzerland, including Promis UK, The Kusnacht Practice, and Paracelsus.',
      'In addition to her clinical work, Patricia is an experienced Clinical Supervisor, BACP Accredited Psychotherapist, member of Addiction Professionals, and an accredited member of the Professional Standards Authority Register.',
      'She believes that recovery becomes possible when people experience safety, compassionate relationships, and evidence-informed clinical care that addresses the whole person rather than simply reducing symptoms.',
    ],
  },
  {
    slug: 'caroline-adams',
    order: 8,
    name: 'Caroline Adams',
    role: 'Somatic Facilitator & Nervous System Regulation Specialist',
    paragraphs: [
      'Caroline "Caro" Adams is a Somatic Facilitator specializing in nervous system regulation, body-based therapies, breathwork, yoga, and mindfulness. Her work helps clients reconnect with their bodies, regulate chronic stress responses, and access deeper levels of healing through embodied therapeutic practice.',
      'Caro believes that many emotional and psychological difficulties are carried not only in the mind but also within the nervous system and body. While insight gained through psychotherapy is essential, lasting change often requires the body to experience safety, regulation, and restoration. The body remembers what the mind has moved past and healing often means giving stuck experience, emotion, and trauma a physical pathway to finally release.',
      'Her approach works on multiple levels at once: using breath, movement, and meditation to support the formation of new neural pathways and help regulate amygdala activity; working with heart coherence to bring hyperaroused states like anxiety and panic back into balance; engaging the lymphatic system through breath and movement to support the body in processing stress-related cortisol; and, as new neural pathways take hold, supporting change believed to extend down to the cellular and epigenetic level. Within this framework, yoga is restructured as a dynamic combination of movement, breath, and meditation, training the nervous system back into its window of tolerance.',
      "Working closely with the multidisciplinary team at The New Practice, Caro integrates yoga, breathwork, somatic meditation, mindful movement, and nervous system regulation into each client's individualized treatment program. Her work complements psychotherapy, trauma treatment, and medical care by helping clients develop greater emotional resilience, self-awareness, and physical wellbeing.",
      'She believes healing is not simply the absence of symptoms but the restoration of connection between mind, body, and life itself.',
    ],
  },
  {
    slug: 'katia-rhainds',
    order: 9,
    name: 'Katia Rhainds',
    role: 'Somatic Nutrition Specialist, Ayurvedic Wellness Counsellor & Private Chef',
    paragraphs: [
      'Katia Rhainds combines therapeutic nutrition, culinary excellence, and nervous system regulation to help clients restore health through nourishment. As a Somatic Nutrition Specialist, Ayurvedic Wellness Counsellor, and private chef, she views food as both biological medicine and an essential part of emotional healing.',
      'Founder of Origin – A Somatic Nutrition Method, Katia has developed an approach that recognizes the relationship between nutrition, trauma, digestion, inflammation, emotional wellbeing, and nervous system regulation.',
      'With more than a decade of experience serving discerning private households and superyacht clients around the world, Katia brings exceptional culinary skill together with a deep understanding of personalized care, discretion, and hospitality.',
      'Working alongside the clinical team, she translates nutritional and biochemical recommendations into practical daily living. Every meal is individually prepared to support recovery from addiction, trauma, eating disorders, burnout, chronic stress, and other complex health concerns.',
      'Drawing upon Ayurvedic principles, contemporary nutritional science, and somatic awareness, Katia creates meal programs that help regulate the nervous system, restore digestive health, reduce inflammation, and encourage a healthier relationship with food.',
    ],
  },
  {
    slug: 'nicolas-neduchal',
    order: 10,
    name: 'Nicolas Neduchal',
    role: 'Somatic Therapist, Bodywork Specialist & Nervous System Regulation Practitioner',
    paragraphs: [
      'Nicolas Neduchal is a Somatic Therapist and Bodywork Specialist whose work focuses on helping clients reconnect with their bodies, regulate their nervous systems, and support recovery from trauma, addiction, burnout, and chronic stress.',
      'He believes that the body often continues carrying the effects of emotional experiences long after the conscious mind has attempted to move forward. By integrating therapeutic touch, body awareness, breath, and mindful movement, Nicolas helps clients develop greater resilience, emotional regulation, and mind-body connection.',
      'As creator of Intuitive Reconnection Massage™, Nicolas has developed an individualized body-centred approach that combines therapeutic bodywork with somatic awareness and relaxation techniques. His work complements psychotherapy and trauma treatment by helping clients reduce chronic tension, improve nervous system regulation, and experience a greater sense of physical and emotional safety.',
      'Working closely with The New Practice’s multidisciplinary team, Nicolas tailors every session to the individual’s clinical needs, recognising that each person’s recovery journey is unique.',
    ],
  },
  {
    slug: 'fernando-escobosa-garcia',
    order: 11,
    name: 'Dr. Fernando Escobosa García',
    role: 'Medical Director, Emergency & Concierge Physician',
    paragraphs: [
      'Dr. Fernando Escobosa García is an experienced physician and medical director with a background spanning emergency medicine, hospital care, medical concierge services, toxicology, addiction management, and the coordination of complex medical care for international and private clients.',
      'Throughout his career, Fernando has held senior medical leadership positions across hospitals, clinics, and the Mexican Red Cross in Tulum, overseeing physicians, nursing teams, paramedics, clinical operations, regulatory compliance, and emergency care.',
      'His private practice includes home and hotel consultations, regenerative and anti-aging medicine, addiction management, emergency planning, medical transportation, and the coordination of laboratories, imaging, specialist care, and surgery. He also has extensive experience providing highly discreet 24/7 medical concierge and medical escort services for VIP clients.',
      'At The New Practice, Fernando works closely with the multidisciplinary team to oversee each client’s medical care, ensuring that treatment is safe, highly individualized, and seamlessly coordinated throughout their recovery.',
      'Known for his calm approach, clinical experience, discretion, and ability to manage complex situations, he provides clients with a reassuring medical presence throughout every stage of treatment.',
    ],
  },
]
