/**
 * Hand-maintained knowledge the parser cannot infer from the client document:
 * page identities, slugs, which paragraph is a lead, where a signature ends a
 * section, how list headings are classified. Everything else is read from the
 * document by scripts/ingest-content.mjs. Keep judgement here, not in the
 * parser, so the generator stays honest and each decision is reviewable.
 */

export const SOURCE_FILE = 'Final Website Instructions_DRAFT Sept 1 2026 .docx.md'
export const OUT_DIR = 'src/content'

export const GENERATED_HEADER =
  '// GENERATED by scripts/ingest-content.mjs from the client document — edit the source or the script, not this file.'

/** The bold all-caps lines that open each page group, exactly as they clean up. */
export const PAGE_MARKERS = {
  'LANDING PAGE // HOME': 'home',
  'ABOUT US PAGE': 'about',
  'OUR PROCESS PAGE': 'process',
  'CLINICAL SERVICES': 'services',
  'OUR TEAM': 'team',
  'SELF-ASSESSMENT SERIES': 'assessments',
  CONTACT: 'contact',
  'A Personal Message // THANK YOU': 'personalMessage',
  'CLOSING SECTION: Cost': 'fees',
}

/**
 * Per-page identity. `lead` names the section whose first paragraph is lifted
 * out as the page lead (it is moved, not copied). `signatureLines` names a
 * section whose final N paragraphs are a signature block, not prose.
 */
export const PAGES = {
  home: { slug: 'home', title: 'Home', file: 'pages/home.ts', constName: 'HOME' },
  about: {
    slug: 'about',
    title: 'About',
    file: 'pages/about.ts',
    constName: 'ABOUT',
    signatureLines: { 'a-message-from-the-founder': 2 },
  },
  process: {
    slug: 'our-process',
    title: 'Our Process',
    file: 'pages/process.ts',
    constName: 'PROCESS',
    lead: 'the-new-practice-experience',
  },
  personalMessage: {
    slug: 'a-personal-message',
    title: 'A Personal Message',
    eyebrow: 'THANK YOU',
    file: 'pages/personal-message.ts',
    constName: 'PERSONAL_MESSAGE',
    introId: 'letter',
    pageSignatureLines: 3,
  },
  fees: { slug: 'fees', title: 'Cost', file: 'pages/fees.ts', constName: 'FEES', introId: 'cost' },
  contact: {
    slug: 'contact',
    title: 'Contact',
    file: 'pages/contact.ts',
    constName: 'CONTACT',
    lead: 'begin-the-conversation',
  },
  services: {
    slug: 'clinical-services',
    title: 'Clinical Services',
    file: 'services.ts',
    constName: 'SERVICES_PAGE',
  },
  team: { slug: 'team', title: 'Team', file: 'team.ts', constName: 'TEAM_PAGE' },
  assessments: {
    slug: 'self-assessment',
    title: 'Self-Assessment',
    file: 'assessments.ts',
    constName: 'ASSESSMENTS_PAGE',
  },
}

export const HOME = {
  /** The document sets the overlay title in caps; the owner's brief asks for title case. Asserted equal ignoring case. */
  heroTitle: 'A New Approach to Wellbeing',
  /** The section whose trailing founder block becomes `contact` (values from brand.ts). */
  contactSection: 'begin-the-conversation',
}

export const CONTACT = {
  /** The section whose blank telephone/email/website lines become `contact`. */
  contactSection: 'confidential-consultation',
  /** PLACEHOLDER — the document leaves the website blank; this is the email domain. */
  websitePlaceholder: 'thenewpractice.health',
}

export const SERVICES = {
  expectedSlugs: [
    'addiction-treatment',
    'trauma-and-complex-trauma',
    'mental-health',
    'eating-disorders',
    'executive-health-and-burnout',
    'biochemical-restoration',
    'somatic-therapies-and-nervous-system-regulation',
    'inner-child-work',
    'recovery-management-and-after-care',
    'interventions-and-crisis-response',
    'family-program',
  ],
  /** A list heading matching this is `mayInclude`; every other list is `treats`. */
  mayIncludePattern: /may include/i,
  /** Subsections whose paragraphs are `Name: description` definitions, split at the first colon. */
  definitionSubsections: { 'trauma-and-complex-trauma': ['trauma-focused-treatment-may-include'] },
}

export const TEAM = {
  membersSection: 'meet-the-team',
  expectedSlugs: [
    'lowell-monkhouse',
    'nathaniel-bruce',
    'elena-vasquez-whitfield',
    'justin-nolan',
    'iona-hames',
    'richard-warren',
    'patricia-heyland',
    'caroline-adams',
    'katia-rhainds',
    'nicolas-neduchal',
    'fernando-escobosa-garcia',
  ],
  honorifics: ['Dr.'],
}

export const ASSESSMENTS = {
  howToSection: 'how-to-complete-the-assessment',
  availableSection: 'available-self-assessments',
  /** The cleaned text line that opens the shared scoring block and the ten questionnaires. */
  questionnaireBlockStart: 'Self Assessment Tool',
  /** Short slugs in document order; the generator asserts each title against `titleStartsWith`. */
  questionnaires: [
    { slug: 'alcohol', titleStartsWith: 'Alcohol Addiction' },
    { slug: 'drugs', titleStartsWith: 'Drug Addiction' },
    { slug: 'gambling', titleStartsWith: 'Gambling Addiction' },
    { slug: 'food', titleStartsWith: 'Food Addiction' },
    { slug: 'eating-disorders', titleStartsWith: 'Eating Disorder Screening' },
    { slug: 'sex-and-pornography', titleStartsWith: 'Sex & Pornography' },
    { slug: 'work', titleStartsWith: 'Work Addiction' },
    { slug: 'social-media-and-technology', titleStartsWith: 'Social Media & Technology' },
    { slug: 'codependency', titleStartsWith: 'Codependency' },
    { slug: 'adult-children', titleStartsWith: 'Adult Children of Alcoholics' },
  ],
  /**
   * The document carries one shared interpretation line, written for alcohol
   * ("problematic alcohol use"). That questionnaire gets it whole; the other
   * nine get only its generic final sentence. See CONTENT-GAPS.
   */
  fullInterpretationSlug: 'alcohol',
  bandKeys: ['mild', 'moderate', 'severe'],
}

/** Paragraph-joining thresholds; see linesToParagraphs in ingest-content.parse.mjs. */
export const JOIN_MIN_LENGTH = 60
export const TERM_MAX_LENGTH = 60
export const PRINT_WIDTH = 100
